### ISSUE TITLE
Disable option

### ISSUE THREAD

**Issue by rishiankush** [hoaphantn7604/react-native-element-dropdown#1]
The module works really good. Only thing I did not find is to disable the options in the dropdown menu or simply disable the menu? Is there a way I can do it with this module?

**Comment by hoaphantn7604** [comment]
I added disable option in version 1.1.1

**Comment by rishiankush** [comment]
working great now! Thanks!

**Comment by naitik-erpbuddies** [comment]
Is there any way to style the disabled dropdown @hoaphantn7604?
