### ISSUE TITLE
Local image for select country crashes the app

### ISSUE THREAD

**Issue by liptonzuma** [hoaphantn7604/react-native-element-dropdown#103]
Warning: Failed prop type: Invalid prop `source` supplied to `Image`, expected one of type [string, number] 
I get this error when I try using local image

**Comment by hoaphantn7604** [comment]
hi @liptonzuma ,
Refer this example:
```js
const local_data = [
  {
    value: '1',
    label: 'Country 1',
    image: require('../images/pictures/default-image.jpg'),
  },
]
```
