### ISSUE TITLE
Different size of the containers?

### ISSUE THREAD

**Issue by markosrx** [hoaphantn7604/react-native-element-dropdown#104]
Is it possible to achieve the size and position of container view(red color in image) and container list(yellow color in image) be different, not aligned? Thanks.
![Screenshot 2022-09-07 at 10 12 09](https://user-images.githubusercontent.com/24739932/188826509-f50ced23-e911-4784-b707-e78deb5e0b0a.png)
![Screenshot 2022-09-07 at 11 27 51](https://user-images.githubusercontent.com/24739932/188843692-eda566f5-7d49-4c1d-b2f8-3a6394d0ecad.png)

**Comment by hoaphantn7604** [comment]
hi @markosrx ,
You can use props "renderItem" to customizable.

**Comment by markosrx** [comment]
Hi @hoaphantn7604, thank you for your response.
Do you mean I can achieve something like in the image below? I am not sure we understand well so just to check.

![Simulator Screen Shot - iPhone 13 Pro Max - 2022-09-07 at 15 14 25](https://user-images.githubusercontent.com/24739932/189665488-392355af-3b7f-4911-bf20-5e4c09c94e9f.png)

**Comment by hoaphantn7604** [comment]
hi @markosrx ,
Your problem been solved? Do you need my support anymore?

**Comment by markosrx** [comment]
Hi @hoaphantn7604, I achieved this on image by patching your library by changing the way how `const left` is used...But after that I replaced  this library and used some picker because I couldn't find the way to use it without patching.

**Comment by dprajapati1179** [comment]
> Hi @hoaphantn7604, thank you for your response. Do you mean I can achieve something like in the image below? I am not sure we understand well so just to check.
> 
> ![Simulator Screen Shot - iPhone 13 Pro Max - 2022-09-07 at 15 14 25](https://user-images.githubusercontent.com/24739932/189665488-392355af-3b7f-4911-bf20-5e4c09c94e9f.png)

Hi, My issue is the same as you described in the above image I want only the icon to display and dropdown for te same but the width needs to pass to get the options container width do you have any solution?

**Comment by nijarv** [comment]
Any solution?

**Comment by hoaphantn7604** [comment]
> Any solution?
Hi @nijarv, 
Refer this example:
https://github.com/hoaphantn7604/react-native-element-dropdown/blob/master/example/src/dropdown/Menu.tsx
![Simulator Screen Shot - iPhone 14 Pro - 2023-02-26 at 13 26 34](https://user-images.githubusercontent.com/50919571/221396094-a66fa0cd-048c-45ad-90b3-7302ab996792.png)

**Comment by nijarv** [comment]
okay, let me check! thank you
