### ISSUE TITLE
[Feature Request] Option to show loading state when dropdown is opened

### ISSUE THREAD

**Issue by Pika-Pool** [hoaphantn7604/react-native-element-dropdown#106]
A `loading`/`isLoading` prop to indicate the data is being fetched from a server. An application might be to load usernames in a particular team in an organisation.

When `loading` is `true`, show a `ActivityIndicator` in the dropdown container instead of the list

**Comment by hoaphantn7604** [comment]
hi @Pika-Pool ,
Refer this example:
```js
   <Dropdown
        ....
        flatListProps={{
          ListEmptyComponent: () => (
            <View>
              <ActivityIndicator size={'large'} color="gray" />
            </View>
          ),
        }}
    />
```

**Comment by hadnet** [comment]
@hoaphantn7604 first of all, thanks for this awesome work. My only request is if you can you export the DropdownProps type in order to use it in wrapper comps.
