### ISSUE TITLE
Touchable/active field is only where the text is

### ISSUE THREAD

**Issue by Bodrie** [hoaphantn7604/react-native-element-dropdown#108]
The only area where you can trigger the dropdown is the text box, which is coloed in blue, the container which is colored in red cant trigger the dropdown. This can be fixed with `width: 100%` in the styles file of `dropdown` class

![Screenshot 15-09-2022](https://user-images.githubusercontent.com/80153626/190394294-3bec9742-39e3-4d33-8dd8-f1c3ae22e079.png)

![image](https://user-images.githubusercontent.com/80153626/190395056-31328f0f-d4ca-42b5-ab19-4c72ee62616e.png)

NB: This is tested on `react-native-web` !

**Comment by hoaphantn7604** [comment]
hi @Bodrie ,
Do you put justifyContent: "center" & alignItems: "center" on View container?

**Comment by Bodrie** [comment]
Hello, @hoaphantn7604,
I've got only `style={{ alignItems: 'center'}}` on the `Dropdown` component

**Comment by hoaphantn7604** [comment]
Hi @Bodrie ,
Try deleting alignItems: 'center' see if this issue is still there?
