### ISSUE TITLE
can i use array of an element for data prop

### ISSUE THREAD

**Issue by mukeshbuwade1** [hoaphantn7604/react-native-element-dropdown#109]
i have data =   ["TEST_COLUMN", "TEST_COLUMN2", "MOBILE_NUMBER", "STATUS"]

is it possible to show in dropdown

**Comment by janshajansha** [comment]
You can pass the data as below

`const formatData = data => {
            let obj = [];
            data.map((val,i) => {
                obj[i] = { 'label' : val, 'value' : val};	
            });
            return obj;
};`
`const data = ["TEST_COLUMN", "TEST_COLUMN2", "MOBILE_NUMBER", "STATUS"];`
`<Dropdown 
        data={formatData(data)} 
        labelField="label"
        valueField="value"
/> `

**Comment by hoaphantn7604** [comment]
hi @janshajansha ,
```js
     <Dropdown
          ...
          labelField="label"
          valueField="value"
      />
```
labelField & valueField is required.
So the input data must be an object in array.

**Comment by hoaphantn7604** [comment]
If there are no more problems. I will close this issue.
