### ISSUE TITLE
Android Navigation Color is changed to default white when dropdown is opened

### ISSUE THREAD

**Issue by saheelsapovadia** [hoaphantn7604/react-native-element-dropdown#111]
I have changed the android bottom navigation color for my app and when I tap and open the dropdown the color changes to white.

![image](https://user-images.githubusercontent.com/59962703/194115217-34e830d1-302f-42ca-94c5-285f052c4b1a.png)

See the bottom back, home and tasks buttons of android.

![image](https://user-images.githubusercontent.com/59962703/194115149-d92f9c7c-cb22-4837-9ae8-59f64c06456b.png)

**Comment by hoaphantn7604** [comment]
hi @saheelsapovadia ,
You can use renderItem to customize text color and add icon.

**Comment by saheelsapovadia** [comment]
@hoaphantn7604 thank you for responding.
Just to be clear, I am having uses with the bottom android system navigation bar.
I have highlighted in the attached screenshot with `yellow`.
 Will renderItem help here?
![screenshot](https://user-images.githubusercontent.com/59962703/195101555-91f2e47d-248d-4a21-9e70-2ff5498cda51.png)

**Comment by hoaphantn7604** [comment]
hi @saheelsapovadia,
Refer there https://github.com/facebook/react-native/issues/29543

**Comment by hoaphantn7604** [comment]
If there are no more problems. I will close this issue.
