### ISSUE TITLE
want to query from database every time the user types instead of loading it first

### ISSUE THREAD

**Issue by Vijay-CareAllianz** [hoaphantn7604/react-native-element-dropdown#112]
I have large data items and they are increasing.
I would like to have a dropdown for that list. And i would like to query based on user search.

How can we achieve this?

Any suggestions/ Solutions

**Comment by hoaphantn7604** [comment]
hi @Vijay-CareAllianz ,
Can you use Props "onChangeText".
Ex:
```js
const [lists, setLists] = useState([]);

const onUpdateData=(keywork)=>{
 // Query data from DB.
setLists(<data from DB>);
}

<Dropdown
...
data={lists}
onChangeText={(keywork)=> {onUpdateData(keywork)}}
/>
```

**Comment by hoaphantn7604** [comment]
If there are no more problems. I will close this issue.
