### ISSUE TITLE
defaulting to value when nothing has been selected

### ISSUE THREAD

**Issue by MIKEANTUMA** [hoaphantn7604/react-native-element-dropdown#114]
hello,

I am using the drop down on a form and if I do not select anything it defaults a value when the form is submitted. is there away to not allow the user to submit if nothing in the drop down has been select. I guess stop the drop down from defaulting to a value?

**Comment by hoaphantn7604** [comment]
hi @MIKEANTUMA ,
I checked your issue. The problem does not exist in this package. Please re-check your code again.
