### ISSUE TITLE
Status bar disappears after forcing my app to stay in light mode

### ISSUE THREAD

**Issue by rick427** [hoaphantn7604/react-native-element-dropdown#116]
Hi, so I needed to force my app to remain in light mode because I haven't catered for a dark mode just yet and i didn't want to break my app styles because some users prefer dark mode over light. However after doing this, each time i focus on the dropdown (i.e tap on it), my status bar disappears. A preview image of the app can be found below, as well as my changes

**Result**
![WhatsApp Image 2022-11-11 at 15 31 07](https://user-images.githubusercontent.com/44168932/201361884-92c5b505-c095-4d8e-b56d-b35ba8b5ff82.jpg)

**styles.xml**
```
<style name="AppTheme" parent="Theme.AppCompat.DayNight.NoActionBar">
    <item name="android:forceDarkAllowed">false</item>
    <item name="android:editTextBackground">@drawable/rn_edit_text_material</item>
  </style>
```

**Custom safe view component**
```
import React from 'react';
import { useIsFocused } from '@react-navigation/native';
import { SafeAreaView, StatusBar, ColorValue, StatusBarStyle } from 'react-native';

type TProps = {
  children: React.ReactNode;
  statusBackground?: ColorValue;
  barStyle?: StatusBarStyle
}

const AppSafeView:React.FC<TProps> = ({children, statusBackground, barStyle="dark-content"}):JSX.Element => {
  const isFocused = useIsFocused();
  return (
    <SafeAreaView style={{flex: 1}}>
      {isFocused && (
        <StatusBar backgroundColor={statusBackground} barStyle={barStyle} />
      )}
      {children}
    </SafeAreaView>
  )
}

export default AppSafeView;
```

Also how can I theme this dropdown to accommodate dark mode ? Just thinking ahead. Thanks

**Comment by hoaphantn7604** [comment]
hi @rick427 ,

 ____Style props can be styled to customize dark mode.
