### ISSUE TITLE
Does not fully support JSON files

### ISSUE THREAD

**Issue by ElHefe3** [hoaphantn7604/react-native-element-dropdown#121]
When I try to use a JSON file as a source of data, everything works fine, until I change the state for any other value (using hooks) on the page, then the selected value of the dropdown list defaults to the first value.

Edit: I managed to solve this problem by setting the value equal to a state 
```tsx
  import * as currencies from './constants/CurrencyData.json';

  const data = Object.values(currencies);
  const [currencyData] = useState(data);
```

But now the initial selection displays blank, and only after making a selection for a second time does the correct value display.

**Comment by hoaphantn7604** [comment]
hi @ElHefe3 ,
Can you send me the full code?
