### ISSUE TITLE
react-native-element-dropdown\src\components\Dropdown

### ISSUE THREAD

**Issue by sam9010** [hoaphantn7604/react-native-element-dropdown#122]
* node_modules\react-native-element-dropdown\src\components\Dropdown(.native|.android.js|.native.js|.js|.android.jsx|.native.jsx|.jsx|.android.json|.native.json|.json|.android.ts|.native.ts|.ts|.android.tsx|.native.tsx|.tsx)
  * node_modules\react-native-element-dropdown\src\components\Dropdown\index(.native|.android.js|.native.js|.js|.android.jsx|.native.jsx|.jsx|.android.json|.native.json|.json|.android.ts|.native.ts|.ts|.android.tsx|.native.tsx|.tsx)
> 1 | import Dropdown from './components/Dropdown';
    |                       ^
  2 | import MultiSelect from './components/MultiSelect';
  3 | import SelectCountry from './components/SelectCountry';

i just install this plugin and i use sample of this code

import {Dropdown} from 'react-native-element-dropdown';

  const [listInventory, setListInventory] = useState([]);
  const [selectInventory, setSelectInventory] = useState(null);

setListInventory([{Id:1,Name:'a'},{Id=2,Name='b'},....]);

return( <Dropdown
              data={listInventory}
              labelField="Id"
              valueField="Name"
              value={selectInventory}
              onChange={item => {
                setSelectInventory(item.Name);
              }}
            />)

**Comment by hoaphantn7604** [comment]
hi @sam9010 ,
I cannot reproduce this issue.

**Comment by sam9010** [comment]
hi, @hoaphantn7604 .
no problem, at last I install it and I worked it
