### ISSUE TITLE
Cannot set the locator strategy for the list in the dropdown component for iOS

### ISSUE THREAD

**Issue by LayMui** [hoaphantn7604/react-native-element-dropdown#124]
I have use 
export const langData = [
  {
    **itemAccessibilityLabelField: 'es',
    itemTestIDField: 'es',**
    label: 'es',
    value: 'es',
  },

const testProperties = (id, disableAccessible = false) => ({
  accessible: !disableAccessible,
  accessibilityLabel: id,
  testID: id,
});

export default testProperties;

<Dropdown
          {...testProperties('langInput')}
          style={styles.dropdown}
          placeholderStyle={styles.placeholderStyle}
          selectedTextStyle={styles.selectedTextStyle}
          inputSearchStyle={styles.inputSearchStyle}
          iconStyle={styles.iconStyle}
          onChange={onSetLanguage}
          **data={langData}**

but I am unable to locate the element of the list using the appium inspector

<img width="1299" alt="Screenshot 2022-12-08 at 3 59 48 PM" src="https://user-images.githubusercontent.com/11436517/206391765-6b01766e-61cd-48b3-a5b8-528466f6205b.png">
<img width="1304" alt="Screenshot 2022-12-08 at 4 00 13 PM" src="https://user-images.githubusercontent.com/11436517/206391777-1c054748-1017-4ff4-a33c-8ccc595e31d8.png">

**Comment by LayMui** [comment]
I think this is due to this element of the dropdown wrap around by TouchableOpacity
```   <TouchableOpacity
            testID={_.get(item, itemTestIDField || labelField)}
            accessible={!!accessibilityLabel}
            accessibilityLabel={_.get(

```

can you remove this TouchableOpacity
so I can access the child elements

https://stackoverflow.com/questions/35290427/react-native-cant-find-child-elements-when-accessible-is-true

**Comment by hoaphantn7604** [comment]
hi @LayMui ,
I'm working on it.

**Comment by hoaphantn7604** [comment]
hi @LayMui ,
This issue is resolved, retry with new release 2.5.1.

**Comment by LayMui** [comment]
hi @hoaphantn7604 
it's still the same
here is code snippet ```export const langData = [
  {
    itemAccessibilityLabelField: 'es',
    itemTestIDField: 'es',
    label: 'es',
    value: 'es',
  },
  {
    itemAccessibilityLabelField: 'en',
    itemTestIDField: 'en',
    label: 'en',
    value: 'en',
  },
  {
    itemAccessibilityLabelField: 'bn',
    itemTestIDField: 'bn',
    label: 'bn',
    value: 'bn',
  }```

``` <View {...testProperties('langInput')}>
          
          <Dropdown
            style={styles.dropdown}
            placeholderStyle={styles.placeholderStyle}
            selectedTextStyle={styles.selectedTextStyle}
            inputSearchStyle={styles.inputSearchStyle}
            iconStyle={styles.iconStyle}
            onChange={onSetLanguage}
            data={langData}
            search
            labelField="label"
            valueField="value"
            value={language}
          />
        </View>
```

**Comment by LayMui** [comment]
<img width="892" alt="Screenshot 2022-12-19 at 12 11 02 PM" src="https://user-images.githubusercontent.com/11436517/208346152-c0bd9be9-dddd-4c6b-b40e-81ad471a53d8.png">

**Comment by LayMui** [comment]
<img width="890" alt="Screenshot 2022-12-19 at 12 13 51 PM" src="https://user-images.githubusercontent.com/11436517/208346269-507bd8f0-9584-483f-bedb-df999efb0108.png">

**Comment by LayMui** [comment]
I think it's to set the accessible=false for TouchableOpacity

this will make the children automatable.
see 
https://docs.uipath.com/test-suite/lang-de/docs/automation-for-react-native-apps

**Comment by LayMui** [comment]
it still the same. 
my code snippet
```
   <Dropdown
            accessiblityLabel="dropDown"
            style={styles.dropdown}
            placeholderStyle={styles.placeholderStyle}
            selectedTextStyle={styles.selectedTextStyle}
            inputSearchStyle={styles.inputSearchStyle}
            iconStyle={styles.iconStyle}
            onChange={onSetLanguage}
            data={langData}
            search
            labelField="label"
            valueField="value"
            value={language}
          />```
<img width="886" alt="Screenshot 2022-12-20 at 4 55 46 PM" src="https://user-images.githubusercontent.com/11436517/208625490-cc07e7a2-85e8-46d9-84fe-ea8110262c1f.png">

**Comment by hoaphantn7604** [comment]
hi @LayMui ,
Refer this example:

<img width="882" alt="Screen Shot 2022-12-22 at 14 14 30" src="https://user-images.githubusercontent.com/50919571/209078512-69aff765-965b-455c-b87c-9b3c635fb3e0.png">


```js
import React, { useState } from 'react';

import { Dropdown } from 'react-native-element-dropdown';
import { StyleSheet, scale } from 'react-native-size-scaling';

const data = [
  { label: 'Item 1', value: '1', itemAccessibility: 'item1' },
  { label: 'Item 2', value: '2', itemAccessibility: 'item2' },
  { label: 'Item 3', value: '3', itemAccessibility: 'item3' },
  { label: 'Item 4', value: '4', itemAccessibility: 'item4' },
  { label: 'Item 5', value: '5', itemAccessibility: 'item5' },
  { label: 'Item 6', value: '6', itemAccessibility: 'item6' },
  { label: 'Item 7', value: '7', itemAccessibility: 'item7' },
  { label: 'Item 8', value: '8', itemAccessibility: 'item8' },
];

const DropdownComponent = () => {
  const [value, setValue] = useState(null);

  return (
    <Dropdown
      style={styles.dropdown}
      placeholderStyle={styles.placeholderStyle}
      selectedTextStyle={styles.selectedTextStyle}
      inputSearchStyle={styles.inputSearchStyle}
      iconStyle={styles.iconStyle}
      data={data}
      search
      maxHeight={scale(200)}
      labelField="label"
      valueField="value"
      placeholder="Select item"
      searchPlaceholder="Search..."
      value={value}
      accessibilityLabel={'dropdown'}
      itemAccessibilityLabelField="itemAccessibility"
      onChange={item => {
        setValue(item.value);
      }}
    />
  );
};

export default DropdownComponent;

const styles = StyleSheet.create({
  dropdown: {
    marginTop: 36,
    height: 50,
    borderBottomColor: 'gray',
    borderBottomWidth: 0.5,
  },
  icon: {
    marginRight: 5,
  },
  placeholderStyle: {
    fontSize: 16,
  },
  selectedTextStyle: {
    fontSize: 16,
  },
  iconStyle: {
    width: 20,
    height: 20,
  },
  inputSearchStyle: {
    height: 40,
    fontSize: 16,
  },
});
```

**Comment by LayMui** [comment]
thanks @hoaphantn7604 
but they are still grouped together. 
what I need is each individual item can be accessed separately

**Comment by LayMui** [comment]
i suspect you need to add the props 
accessible={false} in the flatList component
so my automation API can call the editable textfield within the flatList to set the value

**Comment by MykolCreates** [comment]
> thanks @hoaphantn7604 but they are still grouped together. what I need is each individual item can be accessed separately

Were you able to see each individual item separately. I followed the suggestions from this thread but my inspector was only able to detect the parent FlatList.

>i suspect you need to add the props accessible={false} in the flatList component

I also tried passing accessible={false} to the flatListProp but the result is still the same
