### ISSUE TITLE
On Iphone Selected value is Showing Empty working Fine in simulator using with Expo how to do get dropdown text in right not left

### ISSUE THREAD

**Issue by NikhilSangwan-crimson** [hoaphantn7604/react-native-element-dropdown#125]
![image](https://user-images.githubusercontent.com/98738071/207005297-c2b84a1f-c0a3-47e9-956a-4236c7be49c2.png)
![image](https://user-images.githubusercontent.com/98738071/207005501-c47e4ac0-5d04-4b95-8d36-c48394a583cf.png)

**Comment by hoaphantn7604** [comment]
hi @NikhilSangwan-crimson ,
I cannot reproduce your issue, send me your code.
