### ISSUE TITLE
Using MultiSelect, can't select multiple items at a time. closes after each selected item

### ISSUE THREAD

**Issue by nzadkovsky** [hoaphantn7604/react-native-element-dropdown#127]
Versions: 
 - react-native-element-dropdown@2.5.1
 - react-native@0.69.5
 

   <MultiSelect
        style={[styles.dropdown, isFocus && { borderColor: 'blue' }]}
        placeholderStyle={styles.placeholderStyle}
        selectedTextStyle={styles.selectedTextStyle}
        inputSearchStyle={styles.inputSearchStyle}
        iconStyle={styles.iconStyle}
        search
        data={data}
        value={multi}
        labelField="name"
        valueField="email"
        placeholder="Select item"
        searchPlaceholder="Search..."
        activeColor={'grey'}
        onChange={item => {
            console.log("item selected is: ", item)
            setMulti(item);
        }}  
        onFocus={() => setIsFocus(true)}
        onBlur={() => setIsFocus(false)}              
        selectedStyle={styles.selectedStyle}
    />

After each selection in list, the dropdown list will close. I want to be able to select multiple items in the list at once. How can I do that? 

Any suggestions or help is very appreciated

Thank you

**Comment by hkar19** [comment]
Have you tried to reproduce this in a modal? in my case it rerenders the modal.

**Comment by egecetiner** [comment]
i have the same issue
