### ISSUE TITLE
Dropdown doesn't move when keyboard is open

### ISSUE THREAD

**Issue by Pavel-Ananich** [hoaphantn7604/react-native-element-dropdown#13]
Here is search bar:
![Снимок экрана 2021-10-12 в 13 16 34](https://user-images.githubusercontent.com/86955927/136937822-b0924ac7-b85f-4111-ab76-9a2a4c0363d7.png)

When you click on input, it opens dropdown with new input:
![Снимок экрана 2021-10-12 в 13 22 42](https://user-images.githubusercontent.com/86955927/136938685-132f7ed4-e35d-413e-b8b5-0fe38b6360bc.png)

When you click on "Search", modal moves, but dropdown doesn't:
![Снимок экрана 2021-10-12 в 13 19 49](https://user-images.githubusercontent.com/86955927/136938273-5a7d7c4d-67a7-4ced-b611-c25f5fa32a35.png)
)

Here is the code:
![Снимок экрана 2021-10-12 в 13 21 23](https://user-images.githubusercontent.com/86955927/136938495-86a61400-3de0-4825-a9b6-b036c3121641.png)

**Comment by hoaphantn7604** [comment]
When the dropdown hits the bottom border, the list will rotate up, your issue is that the keyboard covers the search box.
I'm working on it.

**Comment by Pavel-Ananich** [comment]
Now dropdown also moves, thanks!
![Снимок экрана 2021-10-12 в 17 28 37](https://user-images.githubusercontent.com/86955927/136975322-dcd2ea84-0715-4587-9dc1-9129ff45452f.png)

But one problem: when you click on item, it isn't selected. Only the keyboard closes:
![Снимок экрана 2021-10-12 в 17 30 13](https://user-images.githubusercontent.com/86955927/136975617-76039095-6b51-42db-88d0-8d07015037bc.png)

And you have to click on item one more time to select it.

**Comment by Pavel-Ananich** [comment]
![Снимок экрана 2021-10-13 в 12 06 17](https://user-images.githubusercontent.com/86955927/137102771-718123e0-a93a-4547-b317-830938b6c48b.png
![Снимок экрана 2021-10-13 в 12 06 41](https://user-images.githubusercontent.com/86955927/137102850-9a7fce59-bd83-4e91-aa61-171b82f887a5.png)
)

**Comment by Pavel-Ananich** [comment]
latest version is 1.3.3?

And where I have to add LogBox.ignoreAllLogs(true)?

Import LogBox like Dropdown:
    import { Dropdown, LogBox } from 'react-native-element-dropdown'
or put into the component:
    <Dropdown
        LogBox.ignoreAllLogs={true}
    />
?

**Comment by putrairawan992** [comment]
@Pavel-Ananich hey bro, please share code full done fixed.. thanks

**Comment by raahimkhan** [comment]
The keyboard for me still covers the search input in dropdown. What was the fix?
