### ISSUE TITLE
Dropdown position is off and dropdownPosition prop is not working

### ISSUE THREAD

**Issue by dorLottan** [hoaphantn7604/react-native-element-dropdown#132]
Hi,
The position of my dropdown is not in the right place.
When I set 'bottom' or 'auto' in dropdownPosition prop it looks like this (first picture),
And when I set it to 'top, it puts it too high (second picture)

I tried to add marginTop to my listContainer style, it works, but the results are different on different devices 
so it is not practical
I would appreciate your help, thanks

1. bottom or auto
![Screenshot 2023-01-13 at 11 09 23](https://user-images.githubusercontent.com/61886578/212294661-2793a8cd-f600-4f44-a340-24d22e13b7c5.png)
2. top
![Screenshot 2023-01-13 at 11 09 12](https://user-images.githubusercontent.com/61886578/212294705-2ed81617-0281-440a-ac86-354b2a730ede.png)

my code: 

the screen
`const Screen = () => {
  const [value, setValue] = React.useState();

  return (
    <View {styles.Wrapper}>
      <View {styles.Container}>
        <CustomDropdown
          value={value}
          setValue={setValue}
          data={[
            { label: '1', value: '1' },
            { label: '2', value: '2' },
            { label: '3', value: '3' },
            { label: '4', value: '4' },
            { label: '5', value: '5' },
            { label: '6', value: '6' },
            { label: '7', value: '7' },
          ]}
        />

        <CustomDropdown
          value={value}
          setValue={setValue}
          data={[
            { label: '1', value: '1' },
            { label: '2', value: '2' },
            { label: '3', value: '3' },
            { label: '4', value: '4' },
            { label: '5', value: '5' },
            { label: '6', value: '6' },
            { label: '7', value: '7' },
          ]}
        />
      </View>
    </View>
  );
};

export default Screen;

const styles = StyleSheet.create({
  Wrapper: {
    flex: 1,
    backgroundColor: 'gray',
    alignContent: 'center',
    justifyContent: 'center',
  },
  Container: {
    flexDirection: 'row',
    backgroundColor: 'gray',
    justifyContent: 'space-around',
    paddingHorizontal: 20
  },
});`

///////////////

the dropdown component

`const CustomDropdown: React.FC<Props> = ({ data, value, setValue, disabled }) => {
  const renderItem = (item: any) => {
    return (
      <View style={styles.item}>
        <Text>{item.label}</Text>
      </View>
    );
  };

  return (
    <Dropdown
      style={styles.dropdown}
      containerStyle={styles.listContainer}
      itemContainerStyle={styles.itemContainer}
      data={data}
      maxHeight={300}
      labelField="label"
      valueField="value"
      value={value}
      onChange={(item) => {
        setValue(item.value);
      }}
      renderItem={renderItem}
      disable={disabled}
      dropdownPosition="bottom"
      placeholder="dropdown"
    />
  );
};

export default CustomDropdown;

const styles = StyleSheet.create({
  dropdown: {
    width: 150,
    margin: 12,
    height: 44,
    backgroundColor: 'white',
    borderRadius: 12,
    padding: 12,
    shadowColor: '#000',
    shadowOffset: {
      width: 0,
      height: 1,
    },
    shadowOpacity: 0.2,
    shadowRadius: 1.41,
    elevation: 2,
  },
  listContainer: {
    backgroundColor: 'white',
    borderRadius: 8,
  },
  itemContainer: {
    borderRadius: 8,
  },
  item: {
    fontSize: 16,
    padding: 17,
  },
});
`

**Comment by hoaphantn7604** [comment]
hi @dorLottan ,
Please Re-check in latest version.
