### ISSUE TITLE
How can I custom select item. Thank you!

### ISSUE THREAD

**Issue by V-d-H** [hoaphantn7604/react-native-element-dropdown#134]
I'm wanting when I select an item an icon will appear on the right side. I did but when I go to the screen and I select an item whenever it warns me that I cannot update a component while updating another component. Thank you for your help

And this is my code RenderItem

 const renderItem = item => {
    return (
      <View style={styles.item}>
        <Text style={styles.selectedTextStyle}>{item.label}</Text>
        {selected.includes(item.value) ? (
          <Image
            source={require('../Image/ReturnResultWarranty/tickxanh.png')}
            style={{width: (height * 4) / 100, height: (height * 4) / 100}}
          />
        ) : null}
        {selected.length == data.length ? setChecked(true) : setChecked(false)}
      </View>
    );
  };

**Comment by hoaphantn7604** [comment]
hi @V-d-H ,
Please refer example.

https://github.com/hoaphantn7604/react-native-element-dropdown#multiselect-example-2
