### ISSUE TITLE
Inputsearch at the top of dropdown when dropdownPosition={"top"} 

### ISSUE THREAD

**Issue by seema7** [hoaphantn7604/react-native-element-dropdown#136]
I want to have input search box at the top of the list when the  dropdownPosition={"top"} and the list should display at the bottom of search input .Please help

**Comment by hoaphantn7604** [comment]
hi @seema7 ,
This issue is resolved. Install version 2.7.0. Use props "inverted" set false.
```js
   <Dropdown
      {...}
      inverted={false}
   />
```
