### ISSUE TITLE
Size Issue while opening with ref open() for first click

### ISSUE THREAD

**Issue by asifbadeghar54** [hoaphantn7604/react-native-element-dropdown#137]
iam opening dropdown by using ref  dropdown is opening but whenever i click to open its size behaving  diffrent after second click its working properly can any one have solution for this.

https://user-images.githubusercontent.com/39403588/215682897-311eb757-8dd9-4456-8c7f-1146731750f9.mp4

**Comment by hoaphantn7604** [comment]
Hi @asifbadeghar54 
I'm checking on it.

**Comment by hoaphantn7604** [comment]
@asifbadeghar54 , I cannot reproduce this issue. What version are you using?

**Comment by asifbadeghar54** [comment]
iam using latest version 2.5.3

**Comment by hoaphantn7604** [comment]
@asifbadeghar54 Try checking again with version 2.6.0

**Comment by divyangkhatri** [comment]
@hoaphantn7604  this bugs still existed in latest version.
In my case when i open with ref container open take almost 200px from left. from second time open it work properly

**Comment by divyangkhatri** [comment]
@hoaphantn7604 , BTW I fixed this issue if you want i can create PR for it.

**Comment by Jhh910** [comment]
> @hoaphantn7604 , BTW I fixed this issue if you want i can create PR for it.



> @hoaphantn7604 , BTW I fixed this issue if you want i can create PR for it.
How did you solve it

**Comment by divyangkhatri** [comment]
> > @hoaphantn7604 , BTW I fixed this issue if you want i can create PR for it.
> 
> > @hoaphantn7604 , BTW I fixed this issue if you want i can create PR for it.
> > How did you solve it

Tried this patch.
Please NOTE: this patch apply to specific version
[react-native-element-dropdown+2.9.0.patch](https://github.com/user-attachments/files/15542441/react-native-element-dropdown%2B2.9.0.patch)

**Comment by Jhh910** [comment]
> > > @hoaphantn7604 , BTW I fixed this issue if you want i can create PR for it.
> > 
> > 
> > > @hoaphantn7604 , BTW I fixed this issue if you want i can create PR for it.
> > > How did you solve it
> 
> Tried this patch. Please NOTE: this patch apply to specific version [react-native-element-dropdown+2.9.0.patch](https://github.com/user-attachments/files/15542441/react-native-element-dropdown%2B2.9.0.patch)

oh god！  this is my version ：
    "react-native-element-dropdown": "^2.12.0",         Is there any other solution？    thank you very much！

**Comment by divyangkhatri** [comment]
> > > > @hoaphantn7604 , BTW I fixed this issue if you want i can create PR for it.
> > > 
> > > 
> > > > @hoaphantn7604 , BTW I fixed this issue if you want i can create PR for it.
> > > > How did you solve it
> > 
> > 
> > Tried this patch. Please NOTE: this patch apply to specific version [react-native-element-dropdown+2.9.0.patch](https://github.com/user-attachments/files/15542441/react-native-element-dropdown%2B2.9.0.patch)
> 
> oh god！ this is my version ： "react-native-element-dropdown": "^2.12.0", Is there any other solution？ thank you very much！

you can downgrade to patch version.

**Comment by sumitsunilrahate** [comment]
> > > > @hoaphantn7604 , BTW I fixed this issue if you want i can create PR for it.
> > > 
> > > 
> > > > @hoaphantn7604 , BTW I fixed this issue if you want i can create PR for it.
> > > > How did you solve it
> > 
> > 
> > Tried this patch. Please NOTE: this patch apply to specific version [react-native-element-dropdown+2.9.0.patch](https://github.com/user-attachments/files/15542441/react-native-element-dropdown%2B2.9.0.patch)
> 
> oh god！ this is my version ： "react-native-element-dropdown": "^2.12.0", Is there any other solution？ thank you very much！

hi have you find any solution for this i have same version

**Comment by divyangkhatri** [comment]
@sumitsunilrahate Checkout this https://github.com/hoaphantn7604/react-native-element-dropdown/issues/137#issuecomment-2146571867
