### ISSUE TITLE
Keyboard not showing when keyboard hits the border in android 

### ISSUE THREAD

**Issue by NomanUmar** [hoaphantn7604/react-native-element-dropdown#141]
using code 
` <Dropdown
                style={[styles.dropdown]}
                placeholderStyle={styles.placeholderStyle}
                selectedTextStyle={styles.selectedTextStyle}
                inputSearchStyle={styles.inputSearchStyle}
                iconStyle={styles.iconStyle}
                data={stateList as []}
                search
                autoScroll
                maxHeight={300}
                labelField="name"
                valueField="name"
                placeholder={!isFocus ? 'Please select a State' : ''}
                searchPlaceholder="Search State"
                value={values.state}
                onFocus={() => setIsFocus(true)}
                onBlur={() => setIsFocus(false)}
                onChange={item => {
                  setIsFocus(false)
                  setFieldValue('state', item.name)
                  setState(item.name)
                }}
              />
`

https://user-images.githubusercontent.com/34022608/217252493-f0fb6c32-03bd-4be8-b771-f20705838178.mov

**Comment by hoaphantn7604** [comment]
hi @NomanUmar ,
What version are you using?

**Comment by NomanUmar** [comment]
version 2.6.0

**Comment by hoaphantn7604** [comment]
I'm working on it.

**Comment by hoaphantn7604** [comment]
hi @NomanUmar ,
Try set statusBarIsTranslucent={true}.
<Dropdown 
   {...}
   statusBarIsTranslucent={true}
/>

**Comment by HamzaKhan9** [comment]
Hey @hoaphantn7604 
I'm facing the same issue, and I'm using version 2.12.2 in which this props statusBarIsTranslucent don't exist.
Can you please help ?

**Comment by testdropdown** [comment]
> Hey [@hoaphantn7604](https://github.com/hoaphantn7604) I'm facing the same issue, and I'm using version 2.12.2 in which this props statusBarIsTranslucent don't exist. Can you please help ?

Same issue I am facing in android
