### ISSUE TITLE
disable modal or modal close on tapping outside?

### ISSUE THREAD

**Issue by SymntxHomendra51** [hoaphantn7604/react-native-element-dropdown#146]
I've used this multiselect on the bottom of the screen the problem is that when drop down opens it gets cropped by the screen. And when i try to scroll it closes automatically.
I want to disable modal or disable modal close on tapping outside.
Edit: ability to pass props to modal would be better.

**Comment by hoaphantn7604** [comment]
hi @SymntxHomendra51 ,
You can only scroll inside the list container.
