### ISSUE TITLE
Support of `null` values broken due to toString() call in keyExtractor as of v2.6.0

### ISSUE THREAD

**Issue by a-luengen** [hoaphantn7604/react-native-element-dropdown#150]
I was using `null` values in `data` for the Dropdown menu, like this:

```
const data = [
{ label: 'Default', value: null },
{ label: 'Alternative Option', value. 'opt1' }
];
```

Since v2.6.0 the dropdown rendering failes when trying to select a different option.
This is due to the change on how keys are generated for FlatList, introduced in commit 6edef77.

**Comment by hoaphantn7604** [comment]
hi @a-luengen ,
i'm working on it.

**Comment by hoaphantn7604** [comment]
This issue is resolved. Install version 2.7.0

**Comment by a-luengen** [comment]
Thank you :)
