### ISSUE TITLE
Android it is opening differently

### ISSUE THREAD

**Issue by shiv-2810** [hoaphantn7604/react-native-element-dropdown#151]
In android the view is opening far from the dropdown menu

**Comment by papijo** [comment]
i am experiencing the same problem.

**Comment by hambalharis** [comment]
I'm facing the same problem. dropdown list is opening way below from placeholder view when StatusBar is set to translucent, if you set translucent to false it will work.

**Comment by hambalharis** [comment]
@myou11 @hoaphantn7604 
Please look into this issue.

**Comment by hoaphantn7604** [comment]
Hi All,
Use props statusBarIsTranslucent set is true fix this issue.
```js
   <Dropdown 
     {...}
     statusBarIsTranslucent={true}
  />
```

**Comment by hambalharis** [comment]
@hoaphantn7604 yes it works! thanks for responding.

**Comment by testdropdown** [comment]
it is not working
