### ISSUE TITLE
Search example

### ISSUE THREAD

**Issue by sujathasperi2022** [hoaphantn7604/react-native-element-dropdown#152]
Hi could u show an example of using this to do a custom search.
Say below is the dropdown data with label as dial_code 
`{name: 'Afghanistan', dial_code: '+93', code: 'AF', flag: '🇦🇫'},
  {name: 'Albania', dial_code: '+355', code: 'AL', flag: '🇦🇱'},
  {name: 'Algeria', dial_code: '+213', code: 'DZ', flag: '🇩🇿'},
  {name: 'American Samoa', dial_code: '+1', code: 'AS', flag: '🇦🇸'},
  {name: 'Andorra', dial_code: '+376', code: 'AD', flag: '🇦🇩'},
  {name: 'Angola', dial_code: '+244', code: 'AO', flag: '🇦🇴'},
  {name: 'Anguilla', dial_code: '+1', code: 'AI', flag: '🇦🇮'},`
  
  So when I search am getting results aganist dial_code where as I would like to get it for name and dial_code
Is it possible to put a sample code for the above

**Comment by hoaphantn7604** [comment]
hi @sujathasperi2022 ,
You can use props "searchField" in Dropdown version 2.8.0.
