### ISSUE TITLE
How to Clear a Drop Down

### ISSUE THREAD

**Issue by markmccoid** [hoaphantn7604/react-native-element-dropdown#159]
I'm sure I'm missing it, but how do I clear a drop down once an item has been selected?

I know I can set the state being used for the value to "undefined", but is there a method to do it from within the dropdown, like a clear button?

thanks!

**Comment by hoaphantn7604** [comment]
hi @markmccoid ,
You can setState() again data list.

**Comment by NavinSeth** [comment]
It would be a nice feature if we add a "X" appear to the drop down after a value is selected and have the library clear it's internal value. What are your thoughts on potentially converted this issue to a feature request?

**Comment by NavinSeth** [comment]
It would be awesome if there was an "X" icon to clear the value and an optional prop to hide or show it.

**Comment by ignacioscl** [comment]
const handleClean = (item:any) => {
console.log(item)
setValue(null)
}
    return (
      <View>
      {renderLabel()}
      <View style={styles.container}>
        
        <Dropdown
          showsVerticalScrollIndicator={true}
          style={[styles.dropdown]}
          placeholderStyle={styles.placeholderStyle}
          selectedTextStyle={styles.selectedTextStyle}
          inputSearchStyle={styles.inputSearchStyle}
          iconStyle={styles.iconStyle}
          data={data}
          search={false}
          minHeight={300}
          maxHeight={300}
          labelField="label"
          valueField="value"
          placeholder={!isFocus ? 'Select item' : '...'}
          searchPlaceholder="Search..."
          value={value}
          onFocus={() => setIsFocus(true)}
          onBlur={() => setIsFocus(false)}
          onChange={(item:any) => {
            setValue(item.value);
            setIsFocus(false);
          }}
          renderLeftIcon={() => (
            <View style={{paddingRight:7,marginLeft:4,paddingVertical:8,borderRightWidth:1,borderRightColor:inputIconBorderRightColor,marginRight:8}}><FontAwesomeIcon icon={faEdit} style={{color:iconColor}}/></View>
          )}
          renderRightIcon={(item) => {
            return <>
                      <View style={{ flexDirection: 'row', alignItems: 'center' }}>
                        {value && <Text onPress={() => {handleClean(item)}} style={{marginRight:6}}><FontAwesomeIcon icon={faClose} color={"red"}/></Text>}
                        <Text onPress={() => {console.log("clickdown")}} style={{marginRight:10}}>
                          <FontAwesomeIcon icon={faChevronDown} />
                        </Text>
                      </View></>;
          }}
        />
      </View>
      </View>
    );

take a look to renderRightIcon, there is the red close icon when item is selected
