### ISSUE TITLE
[Request] More customizable props

### ISSUE THREAD

**Issue by trqvinh90** [hoaphantn7604/react-native-element-dropdown#16]
Thanks for this great library, it helped me a lot when I am trying to implement a screen.
But it could be more convenient if we can add more customizable props. At this moment I want to style the search box inside the Dropdown ( placeholder & input style, custom search & close icon... ). 
Hope to hear from you soon.

**Comment by hoaphantn7604** [comment]
Thank you!
I will add props for input search.

**Comment by trqvinh90** [comment]
Wow...thanks for quick response. I will check it right now

**Comment by Saichand13** [comment]
I believe it would be great if you included a select all button in the multi select dropdown.
