### ISSUE TITLE
export 'IDropdownRef' (reexported as 'IDropdownRef') was not found in './components/Dropdown/model' (module has no exports)

### ISSUE THREAD

**Issue by Santopelufincho** [hoaphantn7604/react-native-element-dropdown#167]
I am importing the package and just by importing the package, I get the error:

```
Compiled with problems:

ERROR in ./node_modules/react-native-element-dropdown/lib/module/index.js 6:0-79

export 'IDropdownRef' (reexported as 'IDropdownRef') was not found in './components/Dropdown/model' (module has no exports)


ERROR in ./node_modules/react-native-element-dropdown/lib/module/index.js 6:0-79

export 'IMultiSelectRef' (reexported as 'IMultiSelectRef') was not found in './components/MultiSelect/model' (module has no exports)
```

**Comment by elemermelada** [comment]
I'm having the same problem. By looking at the files inside the module, "/components/Dropdown/model.js" has the following:

```JavaScript
export {};
//# sourceMappingURL=model.js.map
```

This has been like this for at least several months. How is this supposed to work?

**Comment by hoaphantn7604** [comment]
hi @Santopelufincho , @elemermelada 

What version are you using?
Could you please provide me with additional details about your code?

**Comment by peterbucci** [comment]
> hi @Santopelufincho , @elemermelada
> 
> What version are you using? Could you please provide me with additional details about your code?

I'm using version 2.9.0

The error goes away when I removed the MultiSelect import. Let me know if you need anything else from me.

```
import React, { useState } from "react";
import { StyleSheet } from "react-native";
import { MultiSelect } from "react-native-element-dropdown";

const DropdownComponent = ({ data }) => {
  const [value, setValue] = useState([]);

  return (
    <MultiSelect
      style={styles.dropdown}
      placeholderStyle={styles.placeholderStyle}
      selectedTextStyle={styles.selectedTextStyle}
      data={data}
      maxHeight={300}
      labelField="label"
      valueField="value"
      placeholder="Sections"
      value={value}
      onChange={(item) => setValue(item)}
      renderSelectedItem={() => <></>}
    />
  );
};

export default DropdownComponent;
```

**Comment by Santopelufincho** [comment]
I think it was an issue with our package json stating that I had the newest version although I did not. @elemermelada this may be the case for you as well. By deleting the file and issuing a new npm install, the problem seems to have disappeared. 

Thank you!
