### ISSUE TITLE
Thêm tính năng đọc svg uri

### ISSUE THREAD

**Issue by ChiBao284** [hoaphantn7604/react-native-element-dropdown#168]
Chỗ này mình có thể thêm hiển thị ảnh dưới dạng  svg uri được ko ạ. Thanks tác giả

**Comment by hoaphantn7604** [comment]
hi @ChiBao284 ,
You can use the. renderLeftIcon, renderRightIcon, and renderItem props to customize.
Ex:
```
  <Drodpown
   {...}
   renderLeftIcon={()=> <Svg/>} // Add your code
  />
```

**Comment by ChiBao284** [comment]
Not working with SelectCountry
