### ISSUE TITLE
Require cycle: node_modules/react-native-element-dropdown/index.ts -> node_modules/react-native-element-dropdown/src/SelectCountry/index.tsx -> node_modules/react-native-element-dropdown/index.ts

### ISSUE THREAD

**Issue by Master-gg-02** [hoaphantn7604/react-native-element-dropdown#17]
Require cycle: node_modules/react-native-element-dropdown/index.ts -> node_modules/react-native-element-dropdown/src/SelectCountry/index.tsx -> node_modules/react-native-element-dropdown/index.ts

node_modules/react-native-element-dropdown/src/SelectCountry/index.tsx 
这个文件下的这句要注释掉,不然会导致循环引用
@hoaphantn7604 
`
//import { Dropdown } from '../../index';
`

**Comment by Master-gg-02** [comment]
> Require cycle: node_modules/react-native-element-dropdown/index.ts -> node_modules/react-native-element-dropdown/src/SelectCountry/index.tsx -> node_modules/react-native-element-dropdown/index.ts
> 
> node_modules/react-native-element-dropdown/src/SelectCountry/index.tsx 这个文件下的这句要注释掉,不然会导致循环引用 @hoaphantn7604 `//import { Dropdown } from '../../index';`

建议，引用Dropdown 文件下的文件，不建议直接引用根目录下的文件

**Comment by hoaphantn7604** [comment]
This error only happen when using source example?

**Comment by sam9010** [comment]
i have this problem
how to fix it?
