### ISSUE TITLE
iOS Bug - dropdownPosition don't working properly ( How To Fix )

### ISSUE THREAD

**Issue by Kaique292** [hoaphantn7604/react-native-element-dropdown#196]
just pass the component inside a view with position: relative and zIndex: 1

![code](https://github.com/hoaphantn7604/react-native-element-dropdown/assets/42048798/66ae21da-167e-4f7f-869a-4b90a4e8fbda)

**Comment by mubarizgh** [comment]
this still does not solve the problem

**Comment by Kaique292** [comment]
So you are applying some different logic in your code, provide a part of the code of how you are using it and how the parent element is styled
