### ISSUE TITLE
Scrolling issue

### ISSUE THREAD

**Issue by rishiankush** [hoaphantn7604/react-native-element-dropdown#2]
When I scroll down and select the dropdown, it also goes down with scroll. Here is the screenshot:
![simulator_screenshot_A1AF98D7-BB90-43DB-A261-2E78ADF8DBD8](https://user-images.githubusercontent.com/25289937/123910666-6a809480-d998-11eb-8399-334739358f03.png)

Please note it happens on selecting model(the first dropdown input)
If I don't scroll down it works fine

**Comment by hoaphantn7604** [comment]
Thank you. I'm working on it.

**Comment by hoaphantn7604** [comment]
I'm fixed, Please install new version 1.1.4

**Comment by singhtrustcom** [comment]
wow, great thanks @hoaphantn7604 

let me update to the new version 

have a great day :)

**Comment by rishiankush** [comment]
Great Thanks!

**Comment by vaishnaviReyna** [comment]
It's a bug from the package it self. Please install the version <= 2.5.3.
