### ISSUE TITLE
Open And Close Dropdown Programatically

### ISSUE THREAD

**Issue by h-assefi** [hoaphantn7604/react-native-element-dropdown#20]
How to close or open dropdown from another event ?

**Comment by hoaphantn7604** [comment]
Please install later version 1.5.3.
<h4 dir="auto" style="box-sizing: border-box; margin-top: 24px; margin-bottom: 16px; font-size: 16px; font-weight: 600; line-height: 1.25; color: rgb(36, 41, 47); font-family: -apple-system, &quot;system-ui&quot;, &quot;Segoe UI&quot;, Helvetica, Arial, sans-serif, &quot;Apple Color Emoji&quot;, &quot;Segoe UI Emoji&quot;; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">Method</h4>

API | Params | Description
-- | -- | --
open | () => void | Open dropdown list
close | () => void | Close dropdown list

**Comment by irenegonzalez27** [comment]
Are there examples of this somewhere, please?
