### ISSUE TITLE
[Android] Navbar being defined to visible with black background when dropdown is visible

### ISSUE THREAD

**Issue by CarlosSLoureiro** [hoaphantn7604/react-native-element-dropdown#210]
I need to change the navigation bar color in the android version of my app to other color. But if the dropdown is visible, it switch to black.
In addition, even if we set the navigation bar to hidden like this:

```
import * as NavigationBar from 'expo-navigation-bar';
NavigationBar.setVisibilityAsync(`hidden`);
```

When the dropdown is visible, it makes the navigation bar also to visible and with black color as background.

**Comment by CarlosSLoureiro** [comment]
Here is a example:

https://github.com/hoaphantn7604/react-native-element-dropdown/assets/19580424/eb917539-818c-444c-8c3d-cf4fa456b2a0

**Comment by carlos3g** [comment]
same

**Comment by carlos3g** [comment]
See: https://github.com/hoaphantn7604/react-native-element-dropdown/issues/111

@CarlosSLoureiro

**Comment by CarlosSLoureiro** [comment]
@carlos3g I'm using expo and I'm building my project with EAS (bare)

I found a way to fix it. Just follow this:

Create a custom plugin:

**Comment by CarlosSLoureiro** [comment]
@carlos3g I'm building my project (Bare) using EAS from expo. 

I found a way to fix it. Just follow this:


Create a custom plugin:

**/plugins/withCustomNavigationBarColor.js**
```
const { AndroidConfig, withAndroidStyles } = require('expo/config-plugins');

const withCustomNavigationBarColor = (config) => {
  return withAndroidStyles(
    config,
    async (config) => {
      // Find "AppTheme" style
      const appTheme = config.modResults.resources.style?.find(
        (style) => style.$.name === `AppTheme`
      );

      // Find item "android:navigationBarColor" in "AppTheme"
      const navigationBarColorItem = appTheme?.item.find(
        (item) => item.$.name === `android:navigationBarColor`
      );

      // If exists, change it's value to "@android:color/transparent"
      if (navigationBarColorItem) {
        navigationBarColorItem._ = `@android:color/transparent`;
      } else {
        // Else create the item
        appTheme?.item.push(
          AndroidConfig.Resources.buildResourceItem({
            name: `android:navigationBarColor`,
            value: `@android:color/transparent`,
          })
        );
      }

      return config;
    }
  );
};

module.exports = withCustomNavigationBarColor;
```

Add this custom plugin in your **app.json**:
```
{
  "expo": {
    "plugins": [
      "./plugins/withCustomNavigationBarColor"
    ],
  }
}
```

This solved my problem.

**Comment by matmartic** [comment]
@CarlosSLoureiro thanks a lot, this solved our issue where the navbar would change color when opening the dropdown
