### ISSUE TITLE
Invariant Violation: scrollToIndex out of range: requested index 101 is out of 0 to 36

### ISSUE THREAD

**Issue by govindshah62** [hoaphantn7604/react-native-element-dropdown#22]
I am using a dropdown for the country data and it contains more than 150 data, without search, it is working fine but with search it is throwing error of " Invariant Violation: scrollToIndex out of range: requested index 101 is
out of 0 to 36 "

import { Dropdown } from 'react-native-element-dropdown';
import { ScrollView, Text, TextInput, View } from 'react-native';

return (
<View style={styles.container}>
          <Text style={[styles.regularText, styles.f15]} numberOfLines={1}>
            Country/Region
          </Text>
          <Dropdown
            style={[styles.dropdown, styles.lightText]}
            data={allCountries}
            labelField="label"
            valueField="label"
            placeholder="Select Country"
            value={country}
            onChange={(item) => {
              setcountry(item.label);
            }}
            renderItem={_renderItem}
            selectedTextStyle={[styles.selectedText, styles.mediumText]}
            placeholderStyle={[styles.selectedText, styles.mediumText]}
            maxHeight={300}
            search
            autoScroll={true}
            searchPlaceholder="Search..."
            inputSearchStyle={{ height: 40, fontSize: 13,  }}
            iconColor={colors.primary}
          />

          {/* <Text style={[styles.regularText, styles.errorTextStyle]}>Error message</Text> */}
        </View>
)
![WhatsApp Image 2021-11-27 at 11 24 44 AM](https://user-images.githubusercontent.com/51223351/143669915-1bb65e12-3da7-4bc6-975c-108ea347f9e8.jpeg)

**Comment by hoaphantn7604** [comment]
I'm working on it.

**Comment by hoaphantn7604** [comment]
This issue has been resolved. Please install later version 1.5.4

**Comment by govindshah62** [comment]
yes now it's working, Thanks !!

**Comment by govindshah62** [comment]
now its again getting the same error if we use 2 dropdowns with search functionality

steps to reproduce:
1). The First dropdown is for country and 2 is for the state
2). Now first search in the country dropdown and then in state dropdown 
3). Now if we again search in the country dropdown it throws the same error

**Comment by hoaphantn7604** [comment]
Thanks, I'm working on it.

**Comment by hoaphantn7604** [comment]
Can you give me sample code?

**Comment by hoaphantn7604** [comment]
I cannot reproduce this error. Please provided video.

**Comment by hoaphantn7604** [comment]
Please install version 1.5.5.
I'm not sure it worked.
You can try again and feedback for me

**Comment by akshy78695** [comment]
I'm also getting this error but only when I set predefine dropdown value, If dropdown value is empty it works perfectly.

react-native-element-version: 1.5.8
react: 17.0.2
react-native: 0.66.4

**Comment by hoaphantn7604** [comment]
hi @akshy78695 ,
I'm working on it.

**Comment by hoaphantn7604** [comment]
hi @akshy78695 ,
I can't reproduce your problem, but i have updated a few things hope it will work for you.
Please instal later version.

**Comment by govindshah62** [comment]
hi @hoaphantn7604 now getting same error with different condition
steps to produce:-
1) Load a list of 250+ elements
2) now search last element and select it 
3) now search for the 1st element and try to select it, it will throw error

**Comment by krishna-kpk** [comment]
In library components Dropdown directory index.tsx file, if you added Flatlist props initialNumToRender={listData.length} then you are able to auto-scroll to 250 or 300 records. Also if we added props for this functionality that's helpful to user who is use this library.

**Comment by floppy1515** [comment]
This dropdown library is great but I have the same problem,
I have a list of 1000 countries when the user quickly presses three letters I find the expression:

 ERROR  Invariant Violation: scrollToIndex out of range: item length 0 but minimum is 1, js engine: hermes
