### ISSUE TITLE
Failure in build.gradle

### ISSUE THREAD

**Issue by h-assefi** [hoaphantn7604/react-native-element-dropdown#23]
FAILURE: Build completed with 2 failures.

1: Task failed with an exception.
-----------
* Where:
Build file 'F:\Test\node_modules\react-native-element-dropdown\android\build.gradle' line: 25

* What went wrong:
A problem occurred evaluating project ':react-native-element-dropdown'.
> Plugin with id 'maven' not found.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
==============================================================================

2: Task failed with an exception.
-----------
* What went wrong:
A problem occurred configuring project ':react-native-element-dropdown'.
> com.android.builder.errors.EvalIssueException: compileSdkVersion is not specified. Please add it to build.gradle

**Comment by hoaphantn7604** [comment]
Step 1: react-native unlink react-native-element-dropdown
Step 2: install later version
If you have any problem, please comment here.
