### ISSUE TITLE
Search input text style

### ISSUE THREAD

**Issue by anniewey** [hoaphantn7604/react-native-element-dropdown#25]
How to change font size and colour for search input text?

**Comment by hoaphantn7604** [comment]
hi @anniewey ,
Use inputSearchStyle props:
inputSearchStyle={{ fontSize: 14 }}

**Comment by anniewey** [comment]
@hoaphantn7604 I have tried using this props earlier but it's not reflecting on the text, the style applied to the search view only.

**Comment by hoaphantn7604** [comment]
hi @anniewey ,
What version are you using?
Instal later version and try again

**Comment by anniewey** [comment]
I'm using `"react-native-element-dropdown": "^1.4.6"`

**Comment by hoaphantn7604** [comment]
That version is old, please update version.
