### ISSUE TITLE
Require local image instead of link

### ISSUE THREAD

**Issue by kriptcs** [hoaphantn7604/react-native-element-dropdown#256]
Greetings,

I have got the package to work smoothly on my app yet I have an issue, I need to reference a local image instead of a link since the app must work offline

`    value: "1",
    lable: "Swedish",
    image: {
      uri: "https://i.imgur.com/lCmlkhG.png",
    },
`

What do I need to do in order to achieve that?

Thank you!

**Comment by nehalprasad** [comment]
I guess you might be using **SelectCountryComponent** .
Inside renderItem of the **SelectCountryComponent**
You can do the following changes   const _renderItem = (item: any) => {
      const isLocalImage = typeof item.image.uri === 'string';
      return (
        <View style={styles.item}>
         <Image
            style={[styles.image, imageStyle]}
            source={isLocalImage ? item[imageField] : item.image.uri}
          />
          <Text style={[styles.selectedTextStyle, selectedTextStyle]}>
            {item[labelField]}
          </Text>
        </View>
      );
    }; 
and you have to pass the local image something like this const local_data = [
  {
    value: '1',
    lable: 'Country 1',
    image: {
      uri: 'https://www.vigcenter.com/public/all/images/default-image.jpg',
    },
  },
  {
    value: '5',
    lable: 'Country 5',
    image: {
      uri: require('./src/tree.jpg'),
    },
  },
];

**Comment by nehalprasad** [comment]
I guess you might be using SelectCountryComponent .
Inside renderItem of the SelectCountryComponent
<img width="373" alt="Screenshot 2024-04-01 at 4 58 20 PM" src="https://github.com/hoaphantn7604/react-native-element-dropdown/assets/100669020/d27941db-37fe-4a13-b3bc-4c520d40412a">

and you have to pass the local image something like this
<img width="394" alt="Screenshot 2024-04-01 at 4 58 58 PM" src="https://github.com/hoaphantn7604/react-native-element-dropdown/assets/100669020/af0727da-54bc-4f0a-b098-2caf55568337">
@kriptcs

**Comment by kriptcs** [comment]
hey @nehalprasad Thank you for your reply. I have used `require(...)`, but it still didn't help. 
I think the issue is in the first screenshot you sent. I do not have that function, where can I find it?
For full context here is how my code looks:

CountrySelector.js

`import React, { useState } from "react";
import { StyleSheet } from "react-native";
import { SelectCountry } from "react-native-element-dropdown";

const local_data = [
  {
    value: "1",
    lable: "English",
    image: {
      source: require("../assets/images/flags/american.jpg"),
    },
  ....
];

const SelectCountryScreen = (_props) => {
  const [country, setCountry] = useState("1");
  const sendToParent = (data) => {
    _props.func(data);
  }; // Unrelated to the issue and the issue still occured even before this.
  return (
    <SelectCountry
      style={styles.dropdown}
      selectedTextStyle={styles.selectedTextStyle}
      placeholderStyle={styles.placeholderStyle}
      imageStyle={styles.imageStyle}
      iconStyle={styles.iconStyle}
      maxHeight={200}
      value={country}
      data={local_data}
      valueField="value"
      labelField="lable"
      imageField="image"
      onChange={(e) => {
        setCountry(e.value);
        sendToParent(e.value);
      }}
    />
  );
};

export default SelectCountryScreen;

const styles = StyleSheet.create({
  dropdown: {
    },
    ....
    

});
`

I have used the [SelectCountry example 2 template.](https://www.npmjs.com/package/react-native-element-dropdown)

**Comment by prasadnehaal** [comment]
@kriptcs Hi, just pass a prop of renderItem inside your SelectCountryComponent
` <SelectCountry
      style={styles.dropdown}
      selectedTextStyle={styles.selectedTextStyle}
      placeholderStyle={styles.placeholderStyle}
      imageStyle={styles.imageStyle}
      iconStyle={styles.iconStyle}
      maxHeight={200}
      value={country}
      data={local_data}
      valueField="value"
      labelField="lable"
      imageField="image"
renderItem={renderItem}
      onChange={(e) => {
        setCountry(e.value);
        sendToParent(e.value);
      }}
    />` 
and create a function renderItem
`const renderItem = (item: any) => {
const isLocalImage = typeof item.image.url === 'string'
      return (
        <View style={styles.item}>
          <Image source={isLocalImage ? item[imageField] : item.image.url} style={[styles.image, imageStyle]} />
          <Text style={[styles.selectedTextStyle, selectedTextStyle]}>
            {item[labelField]}
          </Text>
        </View>
      );
    };`

**Comment by kriptcs** [comment]
Sorry to bother, what is the equivalent of "item: any" in javascript? I am not using typescript and it throws up an error

**Comment by prasadnehaal** [comment]
you can remove it, no use if you are not using typescript

**Comment by kriptcs** [comment]
Alright. It still does not seem to work though..I have pretty much copy pasted both chunks and I have no syntax errors yet I stilll have no image on the dropdown. The only ones that work are the ones that are still uploaded online

**Comment by prasadnehaal** [comment]
Have you created json with image in you local src

**Comment by prasadnehaal** [comment]
like i have done in one of the screenshot above with an array named local_data! something like this
<img width="394" alt="318419528-af0727da-54bc-4f0a-b098-2caf55568337" src="https://github.com/hoaphantn7604/react-native-element-dropdown/assets/148227808/0854cae4-5bc2-48f3-be22-d03d26cdebde">

**Comment by kriptcs** [comment]
I sent my code above, I do have this. It is not a separate file, it is rather in the same .js file as everything else. The problem I think doesn't like in this, because I have 5 of these pieces of data: 4 with a link imgur and 1 with a uri to a local file. The other 4 work as usual and the one with the uri doesn't. I have tried a lot of things: 
`uri: "./path/to/image.jpg"`

`uri: require("./path/to/image.jpg)"`

then tried using "url" instead of "uri" and still nothing.

**Comment by prasadnehaal** [comment]
Can we connect on google meet

**Comment by kriptcs** [comment]
yes in a few minutes if possible

**Comment by prasadnehaal** [comment]
https://meet.google.com/pzx-keqg-rqv?pli=1&ijlm=1712065147722&adhoc=1&hs=187

**Comment by kriptcs** [comment]
@prasadnehaal I am in the meet now

**Comment by nehalprasad** [comment]
@kriptcs Can you send me the local_data of yours again

**Comment by kriptcs** [comment]
const local_data = [
  {
    value: "1",
    lable: "English",
    image: {
      source: require("../assets/images/flags/american.jpg"),
    },
  },
  {
    value: "2",
    lable: "Swedish",
    image: {
      uri: "https://i.imgur.com/lCmlkhG.png",
    },
  },

  {
    value: "3",
    lable: "Japanese",
    image: {
      uri: "https://i.imgur.com/EL9UnZd.png",
    },
  },
  {
    value: "4",
    lable: "Danish",
    image: {
      uri: "https://i.imgur.com/h5lYMuT.png",
    },
  },
  {
    value: "5",
    lable: "Finnish",
    image: {
      uri: "https://i.imgur.com/wGo0ftj.jpeg",
    },
  },
];

@nehalprasad

**Comment by nehalprasad** [comment]
> import React, {useState} from 'react';
import {
  I18nManager,
  Image,
  SafeAreaView,
  StyleSheet,
  Text,
  View,
} from 'react-native';
import {Dropdown} from 'react-native-element-dropdown';

const local_data = [
  {
    value: '1',
    lable: 'India',
    image: {
      uri: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcT7tdv7EvQTq9b4q630tWtlsXw5--lzD2rh_5m8nIBMsw&s',
    },
  },
  {
    value: '2',
    lable: 'Romania',
    image: {
      uri: 'https://upload.wikimedia.org/wikipedia/commons/thumb/7/73/Flag_of_Romania.svg/800px-Flag_of_Romania.svg.png',
    },
  },
  {
    value: '3',
    lable: 'Israel',
    image: {
      uri: 'https://cdn.britannica.com/53/1753-004-03582EDA/Flag-Israel.jpg',
    },
  },
  {
    value: '4',
    lable: 'Sweden',
    image: {
      uri: require('./src/images/Sweden.jpeg'),
    },
  },
  {
    value: '5',
    lable: 'Bermuda',
    image: {
      uri: 'https://cdn.britannica.com/55/69555-050-672A2C54/Flag-Bermuda.jpg',
    },
  },
];

const renderItem = (item: any) => {
  const isLocalImage = typeof item.image.uri === 'string';
  return (
    <View style={styles.item}>
      <Image
        source={isLocalImage ? item.image : item.image.uri}
        style={[styles.image]}
      />
      <Text style={[styles.selectedTextStyle]}>{item.lable}</Text>
    </View>
  );
};

const App = () => {
  const [country, setCountry] = useState('1');

  return (
    <SafeAreaView>
      <Dropdown
        style={styles.dropdown}
        selectedTextStyle={styles.selectedTextStyle}
        placeholderStyle={styles.placeholderStyle}
        inputSearchStyle={styles.inputSearchStyle}
        search
        renderItem={renderItem}
        maxHeight={200}
        value={country}
        data={local_data}
        valueField="value"
        labelField="lable"
        placeholder="Select country"
        searchPlaceholder="Search..."
        onChange={e => {
          setCountry(e.value);
        }}
      />
    </SafeAreaView>
  );
};

export default App;

const styles = StyleSheet.create({
  container: {
    width: 60,
  },
  item: {
    flexDirection: I18nManager.isRTL ? 'row-reverse' : 'row',
    padding: 6,
    alignItems: 'center',
  },
  image: {
    width: 20,
    height: 20,
    marginRight: 3,
    marginVertical: 4,
  },
  selectedTextStyle: {
    flex: 1,
    fontSize: 12,
    writingDirection: I18nManager.isRTL ? 'rtl' : 'ltr',
  },
  dropdown: {
    margin: 16,
    height: 50,
    borderBottomColor: 'gray',
    borderBottomWidth: 0.5,
  },
  imageStyle: {
    width: 24,
    height: 24,
  },
  placeholderStyle: {
    fontSize: 16,
  },
  inputSearchStyle: {
    height: 40,
    fontSize: 16,
  },
});

**Comment by nehalprasad** [comment]
> import React, {useState} from 'react';
import {
  I18nManager,
  Image,
  SafeAreaView,
  StyleSheet,
  Text,
  View,
} from 'react-native';
import {Dropdown} from 'react-native-element-dropdown';
const local_data = [
  {
    value: '1',
    lable: 'India',
    image: {
      uri: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcT7tdv7EvQTq9b4q630tWtlsXw5--lzD2rh_5m8nIBMsw&s',
    },
  },
  {
    value: '2',
    lable: 'Romania',
    image: {
      uri: 'https://upload.wikimedia.org/wikipedia/commons/thumb/7/73/Flag_of_Romania.svg/800px-Flag_of_Romania.svg.png',
    },
  },
  {
    value: '3',
    lable: 'Israel',
    image: {
      uri: 'https://cdn.britannica.com/53/1753-004-03582EDA/Flag-Israel.jpg',
    },
  },
  {
    value: '4',
    lable: 'Sweden',
    image: {
      uri: require('./src/images/Sweden.jpeg'),
    },
  },
  {
    value: '5',
    lable: 'Bermuda',
    image: {
      uri: 'https://cdn.britannica.com/55/69555-050-672A2C54/Flag-Bermuda.jpg',
    },
  },
];
const renderItem = (item: any) => {
  const isLocalImage = typeof item.image.uri === 'string';
  return (
    <View style={styles.item}>
      <Image
        source={isLocalImage ? item.image : item.image.uri}
        style={[styles.image]}
      />
      <Text style={[styles.selectedTextStyle]}>{item.lable}</Text>
    </View>
  );
};
const App = () => {
  const [country, setCountry] = useState('1');
  return (
    <SafeAreaView>
      <Dropdown
        style={styles.dropdown}
        selectedTextStyle={styles.selectedTextStyle}
        placeholderStyle={styles.placeholderStyle}
        inputSearchStyle={styles.inputSearchStyle}
        search
        renderItem={renderItem}
        maxHeight={200}
        value={country}
        data={local_data}
        valueField="value"
        labelField="lable"
        placeholder="Select country"
        searchPlaceholder="Search..."
        onChange={e => {
          setCountry(e.value);
        }}
      />
    </SafeAreaView>
  );
};
export default App;
const styles = StyleSheet.create({
  container: {
    width: 60,
  },
  item: {
    flexDirection: I18nManager.isRTL ? 'row-reverse' : 'row',
    padding: 6,
    alignItems: 'center',
  },
  image: {
    width: 20,
    height: 20,
    marginRight: 3,
    marginVertical: 4,
  },
  selectedTextStyle: {
    flex: 1,
    fontSize: 12,
    writingDirection: I18nManager.isRTL ? 'rtl' : 'ltr',
  },
  dropdown: {
    margin: 16,
    height: 50,
    borderBottomColor: 'gray',
    borderBottomWidth: 0.5,
  },
  imageStyle: {
    width: 24,
    height: 24,
  },
  placeholderStyle: {
    fontSize: 16,
  },
  inputSearchStyle: {
    height: 40,
    fontSize: 16,
  },
});

**Comment by nehalprasad** [comment]
The image path i have chosen is src folder then an image folder and inside that an image with Sweden.jpeg
@kriptcs

**Comment by kriptcs** [comment]
<img width="81" alt="Screenshot 2024-04-02 at 18 59 56" src="https://github.com/hoaphantn7604/react-native-element-dropdown/assets/25370937/72ed33a3-0912-48d5-8324-4918f67b80f5">

It seems to work but the styling is a bit off

**Comment by prasadnehaal** [comment]
Yup I got it. Just pass the style as per your design in the style prop of all the tags

**Comment by nehalprasad** [comment]
Yup I got it. Just pass the style as per your design in the style prop of all the tags

**Comment by kriptcs** [comment]
Greetings, managed to get it styled yet I still have a few issues
1. The dropdown starts off by stating the language name but as soon as I change language it says "Select item" instead.
2. There is no names next to the languages and even though I applied the same styling as before, it all looks different.

<img width="152" alt="Screenshot 2024-04-03 at 11 32 16" src="https://github.com/hoaphantn7604/react-native-element-dropdown/assets/25370937/72de0d8e-65ae-4372-b876-93b4d0ac5879">

**Comment by nehalprasad** [comment]
may i see you code @kriptcs

**Comment by kriptcs** [comment]
I managed to fix it in the end. This is what did it for me
https://stackoverflow.com/questions/78226455/react-native-element-dropdown-doesnt-work-with-local-image

Thank you so much for the time and help @nehalprasad
