### ISSUE TITLE
Opening dropdown with button

### ISSUE THREAD

**Issue by buscanopaul** [hoaphantn7604/react-native-element-dropdown#27]
Hi @hoaphantn7604,

How can I open the Dropdown list using TouchableOpacity outside Dropdown component? Thank you

**Comment by hoaphantn7604** [comment]
hi @buscanopaul ,
https://github.com/hoaphantn7604/react-native-element-dropdown#method

**Comment by buscanopaul** [comment]
Hi @hoaphantn7604,

Do you a sample code on how that works? Thank you

**Comment by hoaphantn7604** [comment]
```js
const myRef = useRef();
myRef?.current?.show();
<Dropdown 
  ref={myRef}
  ...
/>
```

**Comment by buscanopaul** [comment]
> 

Thank you for the help @hoaphantn7604!
