### ISSUE TITLE
Support for defaultProps will be removed. Use JS default parameters instead.

### ISSUE THREAD

**Issue by MadhavKanna** [hoaphantn7604/react-native-element-dropdown#271]
ERROR  Warning: TextInputComponent: Support for defaultProps will be removed from function components in a future major release. Use JavaScript default parameters instead.    
    in TextInputComponent
    in RCTView (created by View)
    in View
    in TouchableWithoutFeedback
    in RCTView (created by View)
    in View
    in RCTView (created by View)
    in View
    in RCTView (created by View)
    in View
    in TouchableWithoutFeedback
    in RCTView (created by View)
    in View (created by AppContainer)
    in RCTView (created by View)
    in View (created by AppContainer)
    in AppContainer (created by Modal)
    in RCTView (created by View)
    in View (created by Modal)
    in VirtualizedListContextResetter (created by Modal)
    in RCTModalHostView (created by Modal)
    in Modal
    in RCTView (created by View)
    in View
    in Unknown (created by DropDownForm)
    in RCTView (created by View)
    in View (created by DropDownForm)
    in DropDownForm (created by ChooseLocationBusiness)
    in RCTView (created by View)
    in View (created by ChooseLocationBusiness)
    in ChooseLocationBusiness
    in Unknown (created by Route(index))
    in Suspense (created by Route(index))
    in Route (created by Route(index))
    in Route(index) (created by SceneView)
    in StaticContainer
    in EnsureSingleNavigator (created by SceneView)
    in SceneView (created by BottomTabView)
    in RCTView (created by View)
    in View (created by Screen)
    in RCTView (created by View)
    in View (created by Background)
    in Background (created by Screen)
    in Screen (created by BottomTabView)
    in RNSScreen (created by Animated(Anonymous))
    in Animated(Anonymous) (created by InnerScreen)
    in Suspender (created by Freeze)
    in Suspense (created by Freeze)
    in Freeze (created by DelayedFreeze)
    in DelayedFreeze (created by InnerScreen)
    in InnerScreen (created by Screen)
    in Screen (created by MaybeScreen)
    in MaybeScreen (created by BottomTabView)
    in RNSScreenContainer (created by ScreenContainer)
    in ScreenContainer (created by MaybeScreenContainer)
    in MaybeScreenContainer (created by BottomTabView)
    in RCTView (created by View)
    in View (created by SafeAreaProviderCompat)
    in SafeAreaProviderCompat (created by BottomTabView)
    in BottomTabView (created by BottomTabNavigator)
    in PreventRemoveProvider (created by NavigationContent)
    in NavigationContent
    in Unknown (created by BottomTabNavigator)
    in BottomTabNavigator
    in Unknown (created by TabLayout)
    in TabLayout
    in Unknown (created by Route((tabs)))
    in Suspense (created by Route((tabs)))
    in Route (created by Route((tabs)))
    in Route((tabs)) (created by SceneView)
    in StaticContainer
    in EnsureSingleNavigator (created by SceneView)
    in SceneView (created by SceneView)
    in RCTView (created by View)
    in View (created by DebugContainer)
    in DebugContainer (created by MaybeNestedStack)
    in MaybeNestedStack (created by SceneView)
    in RCTView (created by View)
    in View (created by SceneView)
    in RNSScreen (created by Animated(Anonymous))
    in Animated(Anonymous) (created by InnerScreen)
    in Suspender (created by Freeze)
    in Suspense (created by Freeze)
    in Freeze (created by DelayedFreeze)
    in DelayedFreeze (created by InnerScreen)
    in InnerScreen (created by Screen)
    in Screen (created by SceneView)
    in SceneView (created by NativeStackViewInner)
    in Suspender (created by Freeze)
    in Suspense (created by Freeze)
    in Freeze (created by DelayedFreeze)
    in DelayedFreeze (created by ScreenStack)
    in RNSScreenStack (created by ScreenStack)
    in ScreenStack (created by NativeStackViewInner)
    in NativeStackViewInner (created by NativeStackView)
    in RCTView (created by View)
    in View (created by SafeAreaProviderCompat)
    in SafeAreaProviderCompat (created by NativeStackView)
    in NativeStackView (created by NativeStackNavigator)
    in PreventRemoveProvider (created by NavigationContent)
    in NavigationContent
    in Unknown (created by NativeStackNavigator)
    in NativeStackNavigator
    in Unknown (created by AppLayout)
    in AppLayout
    in Unknown (created by Route(accessed))
    in Suspense (created by Route(accessed))
    in Route (created by Route(accessed))
    in Route(accessed) (created by SceneView)
    in StaticContainer
    in EnsureSingleNavigator (created by SceneView)
    in SceneView (created by QualifiedSlot)
    in QualifiedSlot (created by DefaultNavigator)
    in PreventRemoveProvider (created by NavigationContent)
    in NavigationContent
    in Unknown (created by QualifiedNavigator)
    in QualifiedNavigator (created by Navigator)
    in Navigator (created by DefaultNavigator)
    in RNCSafeAreaView
    in Unknown (created by DefaultNavigator)
    in DefaultNavigator
    in Unknown (created by Route())
    in Suspense (created by Route())
    in Route (created by Route())
    in Route() (created by ContextNavigator)
    in RNCSafeAreaProvider (created by SafeAreaProvider)
    in SafeAreaProvider (created by wrapper)
    in wrapper (created by ContextNavigator)
    in EnsureSingleNavigator
    in BaseNavigationContainer
    in ThemeProvider
    in NavigationContainerInner (created by ContextNavigator)
    in ContextNavigator (created by ExpoRoot)
    in ExpoRoot (created by App)
    in App (created by ErrorOverlay)
    in ErrorToastContainer (created by ErrorOverlay)
    in ErrorOverlay (created by withDevTools(ErrorOverlay))
    in withDevTools(ErrorOverlay)
    in RCTView (created by View)
    in View (created by AppContainer)
    in RCTView (created by View)
    in View (created by AppContainer)
    in AppContainer
    in main(RootComponent)

This is the error I get when I try to use this component with Expo Go and Typescript. 
Suppose fixed this in a pull request, does the author accept pull requests?

**Comment by gabrielroodriz** [comment]
This also happened to me after I updated to the. Expo 51 and React Native to the latest one

**Comment by AndreiTimofte96** [comment]
same to me. I tried to disable the warning by using logbox, but with no luck.

**Comment by zkteco-home** [comment]
same

**Comment by zkteco-home** [comment]
react-native-paper 5.12.4 will fix it

**Comment by aravind3566** [comment]
use custom props

  renderInputSearch={() => (
              <TextInput
                style={{
                  borderWidth: 0.5,
                  borderColor: '#DDDDDD',
                  paddingHorizontal: 8,
                  marginBottom: 5,
                  margin: 6,
                  height: 45,
                  borderRadius: 5,
                }}
                value={searchText}
                onChangeText={e => {
                  setSearchText(e);
                }}
                placeholder="Search..."
                placeholderTextColor="rgba(0,0,0,.5)"
              />
            )}

**Comment by alexandreperron** [comment]
Are there updates for this issue? Thank you.

**Comment by MadhavKanna** [comment]
The fix is really simple If I'm not wrong - just replace all defaultProps with default parameters(there literally can't be more low hanging fruit if you want to contribute to open source). I'll definitely have the fix by mid July at most. My work project right now has greater priorities, but I'll def have to address this before launch.

**Comment by MadhavKanna** [comment]
Seems like issue has been resolved. I no longer get this warning.

**Comment by AndreiTimofte96** [comment]
I can confirm that the issue is gone after upgrading to version 2.12.1.
