### ISSUE TITLE
Add custom button below search input

### ISSUE THREAD

**Issue by buscanopaul** [hoaphantn7604/react-native-element-dropdown#28]
Hi @hoaphantn7604,

Is it possible that I can add button below search input field?

Below is the sample web design and I want it in react-native also. I want to add "add new customer button".
<img width="478" alt="Screen Shot 2021-12-15 at 10 03 49 AM" src="https://user-images.githubusercontent.com/17734014/146109851-b045ff90-3032-40ba-9b89-19d76eaef352.png">

Hoping for your response. Thank you

**Comment by hoaphantn7604** [comment]
hi @buscanopaul ,
Your request it same as Autocomplete.

**Comment by mathankumars-1929** [comment]
Any solution ?
