### ISSUE TITLE
Please check this scroll issue

### ISSUE THREAD

**Issue by singhtrustcom** [hoaphantn7604/react-native-element-dropdown#3]
![image](https://user-images.githubusercontent.com/78361510/123993969-36739680-d9cd-11eb-922c-2d31c202194b.png)

Whenever I will scroll to the list at first its works fine but a the second time it threw an error

**Comment by hoaphantn7604** [comment]
which version of my package react-native-element-dropdown are you using?

**Comment by singhtrustcom** [comment]
Hi, @hoaphantn7604  thanks for responding to my message.

I am using 
"react-native-element-dropdown": "^1.1.4"*
"react": "16.11.0",
 
one more thing its working fine on ios but on android  its throwing and error 

Thanks

**Comment by hoaphantn7604** [comment]
Thank you. I'm working on it.

**Comment by singhtrustcom** [comment]
@hoaphantn7604  Thanks Great (y)

**Comment by hoaphantn7604** [comment]
I'm fixed, Please install new version 1.1.5

**Comment by singhtrustcom** [comment]
wow, great thanks @hoaphantn7604

let me update to the new version

have a great day :)

**Comment by vaishnaviReyna** [comment]
It's a bug from the package it self. Please install the version <= 2.5.3.
