### ISSUE TITLE
search : true triggers warning : 'Support for defaultProps will be removed from function components in future major release...'

### ISSUE THREAD

**Issue by bpachniewsk1** [hoaphantn7604/react-native-element-dropdown#300]
![image](https://github.com/user-attachments/assets/c0919641-06c6-41c0-bf28-34ca8be6530a)

During development I've noticed 'will be deprecated' warning when passing 'search : true' prop to 'MultiSelect' component from your package. 

```
 ERROR  Warning: TextInputComponent: Support for defaultProps will be removed from function components in a future major release. Use JavaScript default parameters instead.
    in TextInputComponent
```

**Comment by MadhavKanna** [comment]
Pretty sure updating to the latest version solve this error

**Comment by bpachniewsk1** [comment]
you are right, thx
