### ISSUE TITLE
Dropdown data doesn't update when open 

### ISSUE THREAD

**Issue by akshy78695** [hoaphantn7604/react-native-element-dropdown#32]
Hey @hoaphantn7604, first of all thanks for this great library.

  There is just one issue I'm facing is, Dropdown data doesn't get updated when dropdown is open (and data is empty), 
and If dropdown data is updated (for e.g null => array) I have to close dropdown and open it to display data.

Here is the expo link: https://snack.expo.dev/@ak_expo/react-native-element-dropdown.

**Comment by hoaphantn7604** [comment]
I’m working on it

**Comment by hoaphantn7604** [comment]
hi @akshy78695 ,
I'm fixed, please install later version 1.5.6.
