### ISSUE TITLE
state value gets updated automatically (MultiSelect)

### ISSUE THREAD

**Issue by akshy78695** [hoaphantn7604/react-native-element-dropdown#33]
Hey @hoaphantn7604 , 

State value gets updated without using any setState function in onChange ,
If I only print the stateValue in onChange function, It prints the updated value.

Here is expo (check logs) : https://snack.expo.dev/@ak_expo/react-native-element-dropdown

**Comment by hoaphantn7604** [comment]
hi @akshy78695 
I'm working on it

**Comment by hoaphantn7604** [comment]
hi @akshy78695 ,
Sorry for the delay, but I wanted to let you know that this issue has been resolved.

**Comment by akshy78695** [comment]
hi @hoaphantn7604,

Thanks a lot for your work, 

But I think the issue is still persist, 
In following expo I'm printing state before updating, and updating state after a second,
first time works properly But at second time state value automatically updates before the running setState 

**here is the example**: https://snack.expo.dev/@ak_expo/react-native-element-dropdown-1_5_7

**Comment by hoaphantn7604** [comment]
hi @akshy78695 ,
What version are you using?
I can't reproduce your issue

**Comment by akshy78695** [comment]
hi @hoaphantn7604,

I'm using version: 1.5.7,
To reproduce this issue, set following function to onChange 
```
    (item) => {
        console.log(this.state.selected, 'Before update');
        setTimeout(() => {
          this.setState({ selected: item }, () => {
            console.log(this.state.selected, 'After update');
          });
        }, 1000);
      }
```

I'm printing state value before updating state, and updating state after a second,
but when dropdown changes second time, function is printing updated state value before even I update.


Expected behaviour:

* 1st element selected
    [] before update
    ['1'] after update

* 2nd element selected
    ['1'] before update
    ['1', '2'] after update 

Current behaviour:  

* 1st element selected  
    [] before update
    ['1'] after update

* 2nd element selected
    ['1', '2'] before update.   <<
    ['1', '2'] after update 

I just want to know how state is printing updated value when I'm changing state after that.

**Comment by hoaphantn7604** [comment]
hi @akshy78695 ,
I can't reproduce your issue.
<img width="390" alt="Screen Shot 2022-01-08 at 10 43 54" src="https://user-images.githubusercontent.com/50919571/148630428-cab97c48-6b43-45e4-b881-2c41cbdd6e41.png">

**Comment by hoaphantn7604** [comment]
hi @akshy78695 ,
Please instal later version 1.5.8. I fixed a few things.
