### ISSUE TITLE
Dropdown design issue

### ISSUE THREAD

**Issue by manikandana2z** [hoaphantn7604/react-native-element-dropdown#34]
Hi Team, 

           I have found a small UI design issue in your plugin. The issue is in Dropdown. Please replace the view tag with fragment tag for _renderListTop() and _renderListBottom() in src ---> Dropdown ---> index.tsx and remove flex:1 in container from styles.ts. After doing this, the dropdown height is auto set to its items height.

Screenshots for reference:- 
![Screenshot_1640088369](https://user-images.githubusercontent.com/61150279/147444731-09365747-641e-437f-a584-f568b6352af5.png)
![Screenshot 2021-12-27 123024](https://user-images.githubusercontent.com/61150279/147444513-f1ef6656-04f3-429e-a57e-db05b3fe339c.png)

**Comment by hoaphantn7604** [comment]
hi @manikandana2z ,
Since it is not possible to determine exactly how many item the list has, you can use maxHeight to set the height

**Comment by manikandana2z** [comment]
Hi @hoaphantn7604,

     Thanks for you response. I have gone through your plugin and I have came to know about the use of maxHeight to set the height. Let's assume that you have only two items in your list.  As per your code, the two item will render in dropdown and there will some extra spaces below the last item since you have set flex:1 in View tag. My suggestion is that if you remove the flex:1, there won't be any extra spaces created. As you said before, maxHeight can used to set the height if the list has many items

**Comment by hoaphantn7604** [comment]
hi @manikandana2z ,
Thank you,
I will remove flex:1 and test again

**Comment by hoaphantn7604** [comment]
hi @manikandana2z ,
Sorry for the delay.
After removing flex:1 error arise.
![Simulator Screen Shot - iPhone 13 Pro Max - 2022-01-03 at 08 06 29](https://user-images.githubusercontent.com/50919571/147894106-0a9516e9-059e-4d08-b039-d37ac4a5c319.png)

**Comment by Jamal-ReachFirst** [comment]
Use (flexShrink:1) instead of flex:1 will resolve the issue.
Thanks
