### ISSUE TITLE
[SelectCountry] Allow incoming renderItem and renderLeftIcon to override pre-set props

### ISSUE THREAD

**Issue by jte0711** [hoaphantn7604/react-native-element-dropdown#35]
Hi @hoaphantn7604 , good work on the dropdown! 

I have a suggestion to let user to override `renderItem` and `renderLeftIcon` instead of using the default (current) component, this will let user to adjust the design of the component according to their needs.

This is what the `SelectCountry` do currently:

```javascript
return (
    <Dropdown
      ref={ref}
      {...props}
      renderItem={_renderItem}
      renderLeftIcon={() => {
        if (selectItem?.image) {
          return <Image source={selectItem.image} style={[styles.image, imageStyle]} />;
        } else {
          return null;
        }
      }}
    />
  );
```

I'll connect this with the PR I made

**Comment by hoaphantn7604** [comment]
hi @jte0711 ,
You can use the Dropdown element to customize Country element

**Comment by hoaphantn7604** [comment]
hi @jte0711 ,
Country element is fixed design based on Dropdown element, if you want to customize a Country element you can use Dropdown element

**Comment by jte0711** [comment]
@hoaphantn7604 , oh ok thanks for the information
