### ISSUE TITLE
Dropdown placed too far down 

### ISSUE THREAD

**Issue by yudistiraAshadi** [hoaphantn7604/react-native-element-dropdown#39]
Anyone having this issue? I can "fix" this by giving `containerStyle={{marginTop: -60}}`. I'm not sure why it happens.
![image](https://user-images.githubusercontent.com/18660006/149096949-844ba85d-6643-4d34-a7ee-f788c2ecf891.png)

**Comment by hoaphantn7604** [comment]
hi @yudistiraAshadi ,
How can i reproduce this problem

**Comment by hoaphantn7604** [comment]
Maybe this problem is related to status bar height.

**Comment by hoaphantn7604** [comment]
hi @yudistiraAshadi ,
Fix this problem: StatusBar.setTranslucent(false)
