### ISSUE TITLE
Text props

### ISSUE THREAD

**Issue by eiji11** [hoaphantn7604/react-native-element-dropdown#4]
can you add feature to add props to text for the dropdown? it will be good for adding props like numberOfLines and ellipsizeMode

<Text style={[styles.textItem, placeholderStyle, font()]} **_{...this.props.selectedTextProps}_**>
  {currentValue && currentValue[labelField] || placeholder}
</Text>

**Comment by hoaphantn7604** [comment]
Thank you, Please install new version 1.1.14.
