### ISSUE TITLE
Nested object value

### ISSUE THREAD

**Issue by buscanopaul** [hoaphantn7604/react-native-element-dropdown#40]
Hi @hoaphantn7604,

How can I get the value from nested object?

Here's my data it has name under metadata object
![Screen Shot 2022-01-12 at 7 40 49 PM](https://user-images.githubusercontent.com/17734014/149134915-9817449e-d93a-4e09-a3d4-4870e7b440a4.png)

Is it possible that I can get it and put it in labelField="metadata.name"?
![Screen Shot 2022-01-12 at 7 49 13 PM](https://user-images.githubusercontent.com/17734014/149135081-349d7f73-fa97-48de-89e4-8f27684a605d.png)

Regards,
Paul

**Comment by hoaphantn7604** [comment]
hi @buscanopaul ,
You can create function to format data

**Comment by hoaphantn7604** [comment]
hi @buscanopaul ,
Please instal later version.
I've updated.
