### ISSUE TITLE
Customizable LabelField

### ISSUE THREAD

**Issue by h-assefi** [hoaphantn7604/react-native-element-dropdown#41]
It would be a privilege to have ability of customizing Label Field data and it wouldn't be only one filed to display
for example: I like to show the selected item like this,    
"John Smith, 25, California" 
{fullName, age, state}

**Comment by hoaphantn7604** [comment]
hi @h-assefi ,
You can use "renderItem" props. Takes an item from data and renders it into the list.

**Comment by hoaphantn7604** [comment]
You can create function to format data.

**Comment by h-assefi** [comment]
@hoaphantn7604 I have used "renderItem" for the dropdown items. But, what I need is when the item is selected.
Could you give an example about your second response.

**Comment by hoaphantn7604** [comment]
hi @h-assefi 
Example code:
```js
const formatData = data => {
  const cloneData = [...data];
  cloneData.map(e => {
    return {
      key: e.id,
      label: e.fullName + ' ' + e.age,
    };
  });
};
<Dropdown
  data={formatData(list)}
...
>
```

**Comment by h-assefi** [comment]
@hoaphantn7604 THNX for instant reply.

**Comment by vinay-sayone** [comment]
@hoaphantn7604 Is there way to customize the label Text both style wise and component wise ?
