### ISSUE TITLE
Pull to refresh items

### ISSUE THREAD

**Issue by buscanopaul** [hoaphantn7604/react-native-element-dropdown#45]
Hi @hoaphantn7604, Is it possible to implement pull to refresh or refreshControl in the dropdown items? Thank you

**Comment by hoaphantn7604** [comment]
hi @buscanopaul ,
You can use flatListProps.

**Comment by h-assefi** [comment]
Do you have any example of flatListProps ? @hoaphantn7604

**Comment by buscanopaul** [comment]
Hi @hoaphantn7604 , Up for this
