### ISSUE TITLE
Customize the modal style and create custom renderItem callback

### ISSUE THREAD

**Issue by TheSilentHorizon** [hoaphantn7604/react-native-element-dropdown#46]
Is that possible?

1: I want round borders on the modal, is there a way to achieve that?
2: Can I do a custom renderItem callback ?

**Comment by hoaphantn7604** [comment]
hi @TheSilentHorizon ,
1: I want round borders on the modal, is there a way to achieve that? => Use "containerStyle" props
2: Can I do a custom renderItem callback ? => Use "renderItem" props

**Comment by TheSilentHorizon** [comment]
but the listitem triggers a method on click - how can i call it from my renderItem?

**Comment by hoaphantn7604** [comment]
Don't wrap a touchble.
