### ISSUE TITLE
Remove Space on FlatList when there are a small size of elements 

### ISSUE THREAD

**Issue by TheSilentHorizon** [hoaphantn7604/react-native-element-dropdown#47]
So I have three elements in my Dropdown, but it has way too much space.

![image](https://user-images.githubusercontent.com/29006783/151725670-4f06a691-24ea-441b-b02d-ed4388301575.png)

**Comment by hoaphantn7604** [comment]
hi @TheSilentHorizon ,
Use renderItem props customize item.

**Comment by TheSilentHorizon** [comment]
The space above the items is too high. i doubt that that is an issue of the renderItem.
