### ISSUE TITLE
Error while opening the dropdown

### ISSUE THREAD

**Issue by nishtha95** [hoaphantn7604/react-native-element-dropdown#5]
Sometimes dropdown crashes with the below errors
`Invariant Violation: [1297,"RCTView",1,{"height":"<<NaN>>"}]` is not usable as a native method argument
` Invariant Violation: [1295,"RCTView",1,{"height":"<<NaN>>","justifyContent":"flex-end"}]` is not usable as a native method argument

**Comment by hoaphantn7604** [comment]
Can you provide sample code and screenshot?
