### ISSUE TITLE
Dark mode

### ISSUE THREAD

**Issue by mahiruslu** [hoaphantn7604/react-native-element-dropdown#52]
Hello friend,
Firstly thank you for this repo. 
I realized that we can't change styles of dropdown select item menu. See the image below. If there is a way doing this, can you explain to me
<img width="320" alt="Screen Shot 2022-02-21 at 19 44 48" src="https://user-images.githubusercontent.com/23373520/154997092-00f77672-65e3-4474-b079-22a5f53d068a.png">

**Comment by hoaphantn7604** [comment]
Hi @mahiruslu ,
Example code fix this issue:
containerStyle={{ backgroundColor: ‘black’ }}

**Comment by mahiruslu** [comment]
This is works, thank you.

**Comment by BedoEbied** [comment]
@hoaphantn7604 any updates?
It's kinda difficult to manually style the Flat List
