### ISSUE TITLE
Errors in components

### ISSUE THREAD

**Issue by jmstart-up** [hoaphantn7604/react-native-element-dropdown#53]
Issue: When I am running code inspection there are several issues reported:

Errors:

node_modules/react-native-element-dropdown/src/Dropdown/index.tsx:363:7 - error TS2531: Object is possibly 'null'.

363       ref.current.measure((width, height, px, py, fx, fy) => {
          ~~~~~~~~~~~

node_modules/react-native-element-dropdown/src/MultiSelect/index.tsx:348:7 - error TS2531: Object is possibly 'null'.

348       ref.current.measure((width, height, px, py, fx, fy) => {
          ~~~~~~~~~~~

node_modules/react-native-element-dropdown/src/useDeviceOrientation.ts:41:24 - error TS2339: Property 'remove' does not exist on type 'never'.

41       if(susbcription?.remove){
                          ~~~~~~

node_modules/react-native-element-dropdown/src/useDeviceOrientation.ts:42:22 - error TS2339: Property 'remove' does not exist on type 'never'.

42         susbcription.remove();
                        ~~~~~~

Found 4 errors.

**Comment by hoaphantn7604** [comment]
Hi @jmstart-up ,
I’m working on it.

**Comment by hoaphantn7604** [comment]
What is your RN version?

**Comment by SmartArray** [comment]
This happens with Typescript `v4.6.2`
