### ISSUE TITLE
When Searching Cannot read property 'indexOf' of undefined

### ISSUE THREAD

**Issue by h-assefi** [hoaphantn7604/react-native-element-dropdown#54]
I have used Dropdown. When using search input box the error of Cannot read property 'indexOf' of undefined arises.

**Comment by hoaphantn7604** [comment]
Hi @h-assefi ,
Please provide example code.

**Comment by h-assefi** [comment]
`<Dropdown
                data={data}
                labelField="name"
                valueField="id"
                search
                value={selectedData}
                searchPlaceholder='search'
                flatListProps={{
                  onEndReached: () => {
                    retrieveMore();
                  },
                  onEndReachedThreshold: 0.6,
                  ListFooterComponent: () => {
                    if (moreData) {
                      return <ActivityIndicator />;
                    } else {
                      return null;
                    }
                  },
                }}
                onChange={item => {
                  setSelectedData(item.id);
                }}
              />`
![Screenshot_1646715881](https://user-images.githubusercontent.com/43260748/157169879-171f0d41-4da4-455a-aa4e-db724d8a57cf.png)
![Screenshot_1646715930](https://user-images.githubusercontent.com/43260748/157169884-6fa70015-5d4a-443a-8f77-cf5f2df444cb.png)

**Comment by ynzier** [comment]
> Hi @h-assefi , Please provide example code.

Hi, In OnSearch Function > propSearchFunction > labelText got "unidentified" everytime.
I've try to change 
`const dataSearch = data.filter(searchQuery ? propSearchFunction : defaultFilterFunction);` to
`const dataSearch = data.filter((o) =>
                  Object.keys(o).some((k) =>
                    String(o[k]).toLowerCase().includes(keyword.toLowerCase())
                  )
                );`
It's worked.

**Comment by h-assefi** [comment]
@hoaphantn7604 What should I do ?

**Comment by hoaphantn7604** [comment]
Hi @h-assefi ,
I can't reproduce your problems.
Can you provide an example code on Expo?

**Comment by h-assefi** [comment]
@hoaphantn7604 I don't know how to provide example code on Expo. 
How can I do that ?

**Comment by hoaphantn7604** [comment]
hi @h-assefi ,
Same Ex: https://snack.expo.dev/@ivanzm/react-native-element-dropdown-with-keyboardavoidingview

**Comment by h-assefi** [comment]
I found the problem. It was because of the LabelField data that I was passing. One of them was NULL.
