### ISSUE TITLE
Changing righthand icon to show state of dropdown

### ISSUE THREAD

**Issue by colinbes** [hoaphantn7604/react-native-element-dropdown#57]
How do I know state of dropdown box open vs closed in order to set right hand icon.

I could track via onblur and onfocus but there may be better and safer way

**Comment by hoaphantn7604** [comment]
Hi @colinbes ,
Use onBlur and onFocus.

**Comment by colinbes** [comment]
Thanks, that's what I have working. 

For MultiSelect prop's onFocus and onBlur:
 ```
onFocus={() => outcomeFocus.current=true}
onBlur={() => outcomeFocus.current=false}
```

where I used react native' useRef `const outcomeFocus = useRef(false)` as I didn't want to trigger state change and rerender entire page and then for prop  renderRightIconI have
```
renderRightIcon={() => (
    <Icon name={outcomeFocus.current?"close":"info"} />
)}
```
