### ISSUE TITLE
Dropdown props -> valueField not working

### ISSUE THREAD

**Issue by fermetin** [hoaphantn7604/react-native-element-dropdown#6]
Hi, I was trying to use valueField props for control  dynamically my dropdown  components. I have this `Array<Tax>`  objects at below. 

<img width="816" alt="Screen Shot 2021-08-03 at 22 39 35" src="https://user-images.githubusercontent.com/46136231/128075926-0b831cd7-82a3-464d-9afb-8095bef3ccb0.png">

I used value and label field like below

<img width="195" alt="Screen Shot 2021-08-03 at 22 42 20" src="https://user-images.githubusercontent.com/46136231/128076269-cf33eb91-97ed-450c-a589-1b8e7e04ef1f.png">

 Label field is working smoothly but valueField not. I suppose when I write `valueField='value'`  Dropdown itself onChange method `(_value)=>` parameters  should come with my `<Tax>` object key name  which is **value**  but when I tried this way I faced `(_value)=>` parameters came with entirely  `<Tax>`  object

Is there any problem on your code or am I doing something wrong ? Thank you :)

**Comment by hoaphantn7604** [comment]
Thank you. I'm working on it.

**Comment by fermetin** [comment]
I found the solution I will create pull request I hope it will be satisfying for approve :)

**Comment by hoaphantn7604** [comment]
I'm testing the code and doing unit testing

**Comment by hoaphantn7604** [comment]
I have solved this problem, please install new version 1.2.1

**Comment by fermetin** [comment]
> I have solved this problem, please install new version 1.2.1

I saw your solution but you are not still sending `object_item[valueField]` to `onChange` , I think `onChange` argument must be `object_item[valueField]` 

I created PR for this TY 
[https://github.com/hoaphantn7604/react-native-element-dropdown/pull/7](url)

**Comment by hoaphantn7604** [comment]
In some other cases i need to use object_item, if only return object_item['valueField'] then i don't have labelField.
 ```
onChange={item => {
     setDropdown(item.value);
     console.log('selected', item.value);
}}
```
You can use this code to get valueField.

**Comment by fermetin** [comment]
> In some other cases i need to use object_item, if only return object_item['valueField'] then i don't have labelField.
> 
> ```
> onChange={item => {
>     setDropdown(item.value);
>     console.log('selected', item.value);
> }}
> ```
> 
> You can use this code to get valueField.

Why do you need valueField props then ?

**Comment by hoaphantn7604** [comment]
valueField it as a primary key. "labelField" can have the same value but "valueField" cannot be duplicated.

**Comment by hoaphantn7604** [comment]
```
const data = [
  {label: 'Fullname A', value: 1},
  {label: 'Fullname A', value: 2},
  {label: 'Fullname A', value: 3},
  {label: 'Fullname A', value: 4},
  {label: 'Fullname A', value: 5},
  {label: 'Fullname A', value: 6},
  {label: 'Fullname A', value: 7},
  {label: 'Fullname A', value: 8},
];
"labelField" can have the same value but "valueField" cannot be duplicated.

```

**Comment by hoaphantn7604** [comment]
Sorry, maybe my documentation is not detailed.
