### ISSUE TITLE
dropdown is taking the complete screen sometimes even when maxHeight is set to a small number.

### ISSUE THREAD

**Issue by abhinav0031** [hoaphantn7604/react-native-element-dropdown#64]
Everything works fine but sometimes dropdown container just take complete screen's height from top.

**Comment by abhinav0031** [comment]
steps to reproducte:
1. open your app on web.
2.  navigation to a screen where you are using dropdown.
3. Minimize the screen such that dropdown doesn't have enought space below it and now refresh.
4. After refreshing maximize the screen and the dropdown will take complete screen's height.

**Comment by hoaphantn7604** [comment]
hi @abhinav0031 ,
How do i reproduce this problem on mobile device.

**Comment by abhinav0031** [comment]
No this issue doesn't exist in mobile devices, will try to explain. What's happening is that for example when we switch to landscape mode on mobile device and dropdown doesn't have enough space, so it takes complete height of the screen and starts from the top, but when we switch back to portrait mode it behaves fine and doesn't take full screen. But in web it keeps taking full screen from top even when we maximize the screen or it have space.

**Comment by hoaphantn7604** [comment]
hi @abhinav0031 ,
I have never tried this pack on the website before.

**Comment by hoaphantn7604** [comment]
hi @abhinav0031 ,
Please try again with version 1.8.5.

**Comment by abhinav0031** [comment]
no, didn't work still same issue.

**Comment by hoaphantn7604** [comment]
hi @abhinav0031 ,
This issue is resolved in later version.
