### ISSUE TITLE
[MultiSelect] Encountered two children with the same key

### ISSUE THREAD

**Issue by TommysG** [hoaphantn7604/react-native-element-dropdown#65]
When i use the MultiSelect component and i select multiple items withe the same **labelfield**, but with a different **valuefield**, i get this warning _Encountered two children with the same key_ 'Name of label field'. 

I think the problem is, that you have set the labelfield as a key, instead of valuefield inside the renderSelectedItems.

**Comment by hoaphantn7604** [comment]
hi @TommysG ,
Maybe your data has duplicate id.

**Comment by TommysG** [comment]
Yes I have data with duplicate labelField. But should label be unique or only value?

**Comment by DragomirAndrei19** [comment]
I'm facing the same issue, don't know why this was marked as completed.
If you serve this data array, for example, to the MultiSelect component you'll received
```
const myJ = [
  {Name: "GenericName", Id: 1},
  {Name: "GenericName", Id: 2}
]

<MultiSelect 
data={myJ]  
labelField="Name" 
valueField="Id"
renderSelectedItem={(item, unSelect) => (
          <TouchableOpacity onPress={() => unSelect && unSelect(item)}>
            <View style={styles.selectedStyle}>
              <Text style={styles.textSelectedStyle}>{item.Nume}</Text>
              <Image style={{width: 20, height: 20, tintColor: "white"}} source={IMAGES.xCircle}/>
            </View>
          </TouchableOpacity>
        )}
/>
```
So I believe @TommysG is right. Shouldn't the Id field be used?
