### ISSUE TITLE
[Bug]Invariant Violation: scrollToIndex out of range: requested index 170 is out of 0 to 6

### ISSUE THREAD

**Issue by yy412715118** [hoaphantn7604/react-native-element-dropdown#67]
https://user-images.githubusercontent.com/17873134/161186439-40c18fa0-2d0c-4880-9eaa-5b2035cae713.mp4

Hi @hoaphantn7604, This is a useful component, thanks for sharing this, but I found a bug.
Component version: 1.8.5.
Simulator: iPhone13, iOS 15.2
Code:
<Dropdown
                data={phoneList}
                labelField="label"
                valueField="value"
                style={styles.phoneDropdown}
                search
                inputSearchStyle={{ fontSize: 10 }}
                searchPlaceholder="Search"
                selectedTextStyle={styles.selectedTextStyle}
                placeholder={""}
                value={conuntryPhoneCode}
                onChange={function (item: any): void {}}
              ></Dropdown>
Could check this bug? thanks.

**Comment by hoaphantn7604** [comment]
hi @yy412715118 ,
I'm working on it.

**Comment by hoaphantn7604** [comment]
hi @yy412715118 ,
Please check again with a newer version 1.8.7.

**Comment by yy412715118** [comment]
> hi @yy412715118 , Please check again with a newer version 1.8.7.

It's worked. thanks.
