### ISSUE TITLE
[Bug]Invariant Violation: scrollToIndex out of range: requested index 170 is out of 0 to 3

### ISSUE THREAD

**Issue by yy412715118** [hoaphantn7604/react-native-element-dropdown#71]
Version: 1.8.7
Hi @hoaphantn7604 , Look like this issue still exists.

https://user-images.githubusercontent.com/17873134/162128552-8936593a-d55d-4d08-bd9e-ca115a7d735d.mp4

This is my test code:

import {
    ScrollView,
    StyleSheet,
    View,
    KeyboardAvoidingView,
    Platform,
    ActivityIndicator,
  } from "react-native";
  import { observer } from "mobx-react-lite";
  import React, { useContext, useEffect, useState } from "react";
  //"countries-list": "^2.6.1"
  import { countries, Country } from "countries-list";
  import { Dropdown } from "react-native-element-dropdown";
  
  export const UserSignUpScreen = observer(() => {
    const [countryList, setCountryList] = useState<string[]>([]);
    const [phoneList, setPhoneList] = useState<string[]>([]);
    const [conuntryPhoneCode, setConuntryPhoneCode] = useState("64");
    useEffect(() => {
      let c: any[] = [];
      let phones: any = [];
      Object.keys(countries).forEach((key) => {
        let country: Country = countries[key];
        c.push({ label: country.name, value: key });
        phones.push({ label: "+" + country.phone, value: country.phone });
      });
      function setData() {
        setCountryList(c);
        setPhoneList(phones);
      }
      setData();
    }, []);
  
    return (
      <KeyboardAvoidingView
        behavior={Platform.OS === "ios" ? "padding" : "height"}
        style={styles.container}
      >
        <View style={styles.viewContainer}>
        <Dropdown
                  data={phoneList}
                  labelField="label"
                  valueField="value"
                  style={styles.phoneDropdown}
                  search
                  inputSearchStyle={{ fontSize: 10 }}
                  searchPlaceholder="Search"
                  selectedTextStyle={styles.selectedTextStyle}
                  placeholder={""}
                  value={conuntryPhoneCode}
                  onChange={function (item: any): void {
                    setConuntryPhoneCode(item.value)
                  }}
                ></Dropdown>
        </View>
      </KeyboardAvoidingView>
    );
  });
  
  const styles = StyleSheet.create({
    container: {
      flex: 1,
      flexDirection: "column-reverse",
      backgroundColor: "white",
      alignItems: "center",
    },
    viewContainer: {
        backgroundColor: "white",
        borderRadius: 35,
        height: "80%",
        width: "100%",
      },
      selectedTextStyle: {
        fontSize: 12,
        textAlign: "center",
        fontFamily: "Roboto-Medium",
        color: 'green',
      },
    phoneDropdown: {
      width: 70,
      backgroundColor: "#F3F3F3",
    },

  });

**Comment by hoaphantn7604** [comment]
Hi @yy412715118 ,
autoScroll=false,
Temporarily fix the problem.

**Comment by yy412715118** [comment]
> Hi @yy412715118 , autoScroll=false, Temporarily fix the problem.

I tried, but still crash.

**Comment by A-Barkho** [comment]
I have the same Problem.

**Comment by ihonomic** [comment]
> autoScroll=false,

It worked for me. Thanks

**Comment by Vijay-CareAllianz** [comment]
Hi @yy412715118  @hoaphantn7604 facing the same problem here. any solution?

**Comment by Jatinkhandelwal02** [comment]
Hi @yy412715118 @ihonomic @hoaphantn7604, still facing this issue after using autoScroll={false}.
