### ISSUE TITLE
Dropdown is not closing on hardware back button press

### ISSUE THREAD

**Issue by chinmay4github1987** [hoaphantn7604/react-native-element-dropdown#73]
Hardware back button is not functional when Dropdown is opened.

**Comment by hoaphantn7604** [comment]
Hi @chinmay4github1987 ,
I’m working on it.

**Comment by hoaphantn7604** [comment]
hi @chinmay4github1987 ,
This issue is resolved.

**Comment by chinmay4github1987** [comment]
How to achieve this?

**Comment by chinmay4github1987** [comment]
Again I have to reinstall the package?

**Comment by hoaphantn7604** [comment]
Hi @chinmay4github1987 ,
Reinstall this package
