### ISSUE TITLE
Unused '@ts-expect-error' directive

### ISSUE THREAD

**Issue by SmartArray** [hoaphantn7604/react-native-element-dropdown#74]
We get the following `tsc` errors.

```
node_modules/react-native-element-dropdown/src/useDeviceOrientation.ts:27:7 - error TS2578: Unused '@ts-expect-error' directive.

27       // @ts-expect-error - React Native >= 0.65
         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

node_modules/react-native-element-dropdown/src/useDeviceOrientation.ts:29:9 - error TS2578: Unused '@ts-expect-error' directive.

29         // @ts-expect-error - need update @types/react-native@0.65.x
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

```

https://github.com/hoaphantn7604/react-native-element-dropdown/blob/7949771f92088fea60495bd0dac7af55950ea49c/src/useDeviceOrientation.ts#L27-L35

Any ideas what is causing that?

**Comment by hoaphantn7604** [comment]
hi @SmartArray ,

Try upgrading devDependencies.

```js
"devDependencies": {
    "@types/react-native": "*",
  },
```

**Comment by SmartArray** [comment]
Thanks for your response.

My devDependencies are up to date.

Looking at line 27, why would my project throw an error when it's using React Native 0.67 for instance?

**Comment by devpascoe** [comment]
Hey there, also facing this issue.

**Comment by devpascoe** [comment]
Do you think we need "// @ts-expect-error" on these lines mentioned above in useDeviceOrientation.ts ?

**Comment by jcerone-boom** [comment]
An alternative way around this is to change just that file and track the change via git. Then, when you `yarn install` the package, you can use a `post install` script to update the file to fix it. 

Here's what I did:

1. Add the file in question to `git` via: `git add node_modules/react-native-element-dropdown/src/useDeviceOrientation.ts -f`
2. Remove the comments and push up the change
3. Pin my version of `react-native-element-dropdown` in my `package.json` (in my case, to `1.8.12`)
4. Add `postinstall` to `scripts` in `package.json`, having it run `git checkout node_modules/react-native-element-dropdown/src/useDeviceOrientation.ts`. 

The [postinstall](https://yarnpkg.com/advanced/lifecycle-scripts) runs after every install kicked off by yarn. So effectively, I version controlled that file, updated it so `yarn tsc` works, then pulled down that update automatically whenever `yarn` is called and the package goes in.

**Comment by hoaphantn7604** [comment]
Hi,
@ts-expect-err has been removed in version 2.0.

**Comment by hoaphantn7604** [comment]
Hi @jcerone-boom ,
Version 2.0.0 has been release.
