### ISSUE TITLE
[Question] Too much space at the bottom of the list

### ISSUE THREAD

**Issue by nospipi** [hoaphantn7604/react-native-element-dropdown#77]
<img width="157" alt="Screenshot 2022-05-16 at 20 33 40" src="https://user-images.githubusercontent.com/62842853/168650404-87557b3d-e400-4187-935e-cb2b4da77961.png">

Do you know why i'm getting so much space at the bottom of the list ?
Is there a way for the height to be as much as the content of the list ? I have set max height to 400 and it takes it all,even though the items take less space

Thanks in advance !!

**Comment by hoaphantn7604** [comment]
Hi @nospipi ,
Are you using containerStyle it will override the css.

**Comment by nospipi** [comment]
> containerStyle
hi,no i'm not using the containerStyle prop,forked your project now,,i'm trying to dive into the code to see whats causing it,if you have any ideas let me know

**Comment by nospipi** [comment]
Solved it by removing `flex:1` in your `_renderListBottom` function container view,as well the same in your Dropdown `styles.container`,changes can be seen in my fork.

**Comment by hoaphantn7604** [comment]
hi @nospipi ,
How can I reproduce this problem?

**Comment by nospipi** [comment]
> hi @nospipi , How can I reproduce this problem?

here : https://snack.expo.dev/@nospipi/react-native-elements-dropdown

**Comment by nospipi** [comment]
@hoaphantn7604 i fixed the issue by changing your src/Dropdown/styles.ts **styles.container** `flex:1` to `flexShrink:1`
Also i have added a new `shouldChangePlaceholder` boolean prop,where someone can specify if they want the placeholder text to change with the `onChange` event or not.
Check it out and feel free to suggest different prop naming !

**Comment by nospipi** [comment]
@hoaphantn7604
i fixed the issue by changing your src/Dropdown/styles.ts styles.container flex:1 to flexShrink:1 as well as the _renderListBottom component in your index.tsx of the same directory.

Also i have added a new shouldChangePlaceholder boolean prop,where someone can specify if they want the placeholder text to change with the onChange event or not.

Check it out in my fork and feel free to suggest different prop naming !

**Comment by hoaphantn7604** [comment]
@nospipi 
Great!, I changed flex:1 to flexShrink:1
