### ISSUE TITLE
on Android there is an unwanted gap between dropdown and items container

### ISSUE THREAD

**Issue by ranYaar** [hoaphantn7604/react-native-element-dropdown#78]
![image](https://user-images.githubusercontent.com/101973832/168799793-0b15a8a1-707a-4694-ae56-955e4f1c2049.png)

**Comment by hoaphantn7604** [comment]
hi @ranYaar ,
StatusBar.setTranslucent(false) fixes this problem.

**Comment by sagarkbluebenz** [comment]
but where to use it

**Comment by hoaphantn7604** [comment]
Hi @FSV92 ,
Use statusBarIsTranslucent=true in Dropdown props.

**Comment by pharmgarant** [comment]
> 
do you need to use a StatusBar.setTranslucent(false) at the same time?

**Comment by FSV92** [comment]
> Hi @FSV92 , Use statusBarIsTranslucent=true in Dropdown props.


do you need to use a StatusBar.setTranslucent(false) at the same time?

**Comment by hoaphantn7604** [comment]
> > Hi @FSV92 , Use statusBarIsTranslucent=true in Dropdown props.
> 
> do you need to use a StatusBar.setTranslucent(false) at the same time?

Just set statusBarIsTranslucent=true

**Comment by fmording** [comment]
> > Hi @FSV92 , Use statusBarIsTranslucent=true in Dropdown props.
> 
> do you need to use a StatusBar.setTranslucent(false) at the same time?

I found that when statusbar is not translucent, then i need to set it to false. If not, the gap appears on those dropdowns. So, for me at least, I had to make the prop true only in some usecases.

**Comment by FSV92** [comment]
Hi, everyone!
The problem has been solved! Right statusBarIsTranslucent=**{**true**}**

**Comment by Audrey-Ann** [comment]
Hi! When `search` is **true** and the **focus** is on the search input, then the gap reappears even with `statusBarIsTranslucent = true` :/
