### ISSUE TITLE
Want to add custom item if search not found

### ISSUE THREAD

**Issue by sagarkbluebenz** [hoaphantn7604/react-native-element-dropdown#79]
Hi im rendering a list .. if user search the list and he doesn't find the item.. then he can add that custom item.. is it possible?

**Comment by sagarkbluebenz** [comment]
Still Cannot add. Only showing List is empty...

**Comment by glaucomp** [comment]
Same issue

**Comment by developer8530** [comment]
text showing in reverse when dropdownPosition="top" selected
![1675320519967](https://user-images.githubusercontent.com/94797363/216252210-3f840293-3026-4493-87b9-dc393439c083.JPEG)

**Comment by hoaphantn7604** [comment]
> text showing in reverse when dropdownPosition="top" selected ![1675320519967](https://user-images.githubusercontent.com/94797363/216252210-3f840293-3026-4493-87b9-dc393439c083.JPEG)

Hi @developer8530 , Install later version 2.7.0. Use inverted set is "false".
```js
   <Dropdown
      {...}
      inverted={flase}
   />
```
