### ISSUE TITLE
[Android] Android app is crashing while opening modal

### ISSUE THREAD

**Issue by tamangsuresh** [hoaphantn7604/react-native-element-dropdown#8]
IOS app is working fine but android is crashing.
<img width="348" alt="Screen Shot 2021-09-14 at 1 42 47 PM" src="https://user-images.githubusercontent.com/21368268/133219009-80caa0e3-8d8c-4373-8a86-d408ac3f0c56.png">
<img width="394" alt="Screen Shot 2021-09-14 at 1 44 53 PM" src="https://user-images.githubusercontent.com/21368268/133219186-b8048285-6fc5-4ee0-b3f3-fa2fd70debdd.png">
<img width="769" alt="Screen Shot 2021-09-14 at 1 45 08 PM" src="https://user-images.githubusercontent.com/21368268/133219218-73fe48e1-90d7-4873-8087-da7f3afecfb0.png">

**Comment by hoaphantn7604** [comment]
Please install new version 1.2.2
