### ISSUE TITLE
Dropdown view coming from the right of screen

### ISSUE THREAD

**Issue by lucaskab** [hoaphantn7604/react-native-element-dropdown#84]
Hi, I implemented the component in my app but when I click for the first time to open the dropdown, the dropdown come from the right of the screen, and this bug only occurs in the first click, when you close the dropdown and open it again, it works completely fine, what should I do?

**Comment by hoaphantn7604** [comment]
hi @lucaskab ,
I haven't had this problem yet.
Can you send code example?

**Comment by vikramkaldoke** [comment]
Yes! I found same issue.

**Comment by Sirojiddin96** [comment]
Yeah, I have the same problem as well
Can you help me to solve this problem?
@hoaphantn7604 
thank you

![Simulator Screen Shot - iPhone 12 - 2022-07-25 at 21 35 07](https://user-images.githubusercontent.com/26593134/180778795-704a9152-5134-4277-9636-dc745c33e8d8.png)
.

**Comment by hoaphantn7604** [comment]
Hi @Sirojiddin96 ,
Can you send full code example?
