### ISSUE TITLE
Problem opening the keyboard on android

### ISSUE THREAD

**Issue by KovalovIE** [hoaphantn7604/react-native-element-dropdown#86]
Hi!
If the input to search is under the keyboard, it stops opening after one time or if we close the dropdown.
If the search input is outside the keyboard area, everything works correctly.
Video and code attached (I use your example and added some views).

Also, if there is not enough space to the bottom of the screen for maxHeight, the dropdown does not open

react-native - "0.68.1"
react-native-element-dropdown - "1.8.12"

https://user-images.githubusercontent.com/34504672/171280066-05ba0a85-4a77-4bed-822c-001631e4a25e.mp4

import React, { useState } from 'react';
import { StyleSheet, View } from 'react-native';
import { Dropdown } from 'react-native-element-dropdown';

const data = [
    { label: 'Item 1', value: '1' },
    { label: 'Item 2', value: '2' },
    { label: 'Item 3', value: '3' },
    { label: 'Item 4', value: '4' },
    { label: 'Item 5', value: '5' },
    { label: 'Item 6', value: '6' },
    { label: 'Item 7', value: '7' },
    { label: 'Item 8', value: '8' },
];

export const App = () => {
    const [value, setValue] = useState(null);

    return (
        <>
            <View style={{width: '100%', height: 200, backgroundColor: 'red'}}></View>
            <View style={{width: '100%', height: 200, backgroundColor: 'yellow'}}></View>
            <Dropdown
                style={styles.dropdown}
                placeholderStyle={styles.placeholderStyle}
                selectedTextStyle={styles.selectedTextStyle}
                inputSearchStyle={styles.inputSearchStyle}
                iconStyle={styles.iconStyle}
                data={data}
                search
                maxHeight={200}
                labelField="label"
                valueField="value"
                placeholder="Select item"
                searchPlaceholder="Search..."
                value={value}
                onChange={item => {
                    setValue(item.value);
                }}
                renderLeftIcon={() => (
                    null
                )}
            />
        </>
    );
};

const styles = StyleSheet.create({
    dropdown: {
        margin: 16,
        height: 50,
        borderBottomColor: 'gray',
        borderBottomWidth: 0.5,
    },
    icon: {
        marginRight: 5,
    },
    placeholderStyle: {
        fontSize: 16,
    },
    selectedTextStyle: {
        fontSize: 16,
    },
    iconStyle: {
        width: 20,
        height: 20,
    },
    inputSearchStyle: {
        height: 40,
        fontSize: 16,
    },
});

**Comment by hoaphantn7604** [comment]
hi @KovalovIE ,
Please instal later version 2.0.0.

**Comment by najaranas** [comment]
i have the same issue with version ^2.12.4

**Comment by eisodev-r** [comment]
> i have the same issue with version ^2.12.4

Same issue here **on Android only**. Started when I upgraded to from React Native 0.73 to React Native 0.77.3. Happens both on 2.12.2 and 2.12.14. It can be replicated if the components search field is further down in the viewport. It does not happen if the search field is high enough upwards. Happens both inside a tab navigator hosted screen as well as a stack navigator screen without tabs.

Will have to upgrade to 0.80 or higher anyway, so maybe this fixes itself then. Hard to "do anything" on unsupported version of react-native.

Did you try this issue on newer RN versions @hoaphantn7604 ?
