### ISSUE TITLE
Can't style the selected item component

### ISSUE THREAD

**Issue by julekgwa** [hoaphantn7604/react-native-element-dropdown#88]
The selected item component can't be styled when using the Dropdown,  there's selectedStyle  prop for multiselect but it isn't passed to the Dropdown component.

![Screenshot_20220605-133616](https://user-images.githubusercontent.com/5516477/172048836-ebe441bb-7af0-4661-b3e4-65081a117893.png)

**Comment by lakhwinderdebut** [comment]
I have the same issue, but in my case I can't style anything except the border

<Dropdown
        data={users}
        style={styles.dropdown}
        placeholderStyle={styles.placeholderStyle}
        selectedTextStyle={styles.selectedTextStyle}
        inputSearchStyle={styles.inputSearchStyle}
        iconStyle={styles.iconStyle}
        maxHeight={300}
        labelField="label"
        valueField="value"
        placeholder="Select item"
        searchPlaceholder="Search..."
        onChange={item => {
          setUserID(item.id);
        }}
      />


Styles: 
dropdown: {
    margin: 16,
    height: 50,
    borderBottomColor: 'gray',
    borderBottomWidth: 0.5,
  },
  icon: {
    marginRight: 5,
  },
  placeholderStyle: {
    fontSize: 16,
  },
  selectedTextStyle: {
    fontSize: 16,
  },
  iconStyle: {
    width: 20,
    height: 20,
  },
  inputSearchStyle: {
    height: 40,
    fontSize: 16,
  },


![Simulator Screen Shot - iPhone 13 - 2022-06-09 at 15 09 17](https://user-images.githubusercontent.com/11435085/172817119-8c36a132-fade-4a27-b36b-369cd25e4549.png)

**Comment by hoaphantn7604** [comment]
hi @julekgwa , @lakhwinderdebut ,
Pease install later version 2.0.0.
Use the "renderItem" props to customize the item.

**Comment by Gyanprakash73** [comment]
> The selected item component can't be styled when using the Dropdown, there's selectedStyle prop for multiselect but it isn't passed to the Dropdown component.
> 
> ![Screenshot_20220605-133616](https://user-images.githubusercontent.com/5516477/172048836-ebe441bb-7af0-4661-b3e4-65081a117893.png)

use this :--

activeColor={'red'}
