### ISSUE TITLE
This repo should have a changelog

### ISSUE THREAD

**Issue by navarroaxel** [hoaphantn7604/react-native-element-dropdown#91]
It's really hard to track changes on this package based on the Git history.

Could you please include changes in the GitHub [Releases page](https://github.com/hoaphantn7604/react-native-element-dropdown/releases)? or add a `CHANGELOG.md` file to this repository?

**Comment by hoaphantn7604** [comment]
Hi @navarroaxel ,
I will add the release notes in the next release.
