### ISSUE TITLE
MultiSelect Dropdown after selecting the items not close on clicking outside or sliding up Dropdown in closing

### ISSUE THREAD

**Issue by chinmay4github1987** [hoaphantn7604/react-native-element-dropdown#92]
MultiSelect Dropdown after selecting the items not close on clicking outside or sliding up dropdown in closing making the app not user-friendly. Can you check if multi items also get selected in the Text Input field it should automatically show a number of items gets selected?

**Comment by hoaphantn7604** [comment]
Hi @chinmay4github1987 ,
Can you send a short video?
