### ISSUE TITLE
Selected Item is above the drop down container

### ISSUE THREAD

**Issue by newyorksoul** [hoaphantn7604/react-native-element-dropdown#93]
It's more obvious on scroll when the border radius is rounded and the selected item is squared up

![image](https://user-images.githubusercontent.com/45617091/174165802-c8024589-660c-4c28-bde8-43288be64b3a.png)

**Comment by hoaphantn7604** [comment]
Hi @newyorksoul ,
Use containerStyle set paddingBottom.

**Comment by ezze** [comment]
@hoaphantn7604 What if I don't want additional padding at the top/bottom?

**Comment by DenisDov** [comment]
try to set
 ```
boderRadius: number;
overflow: 'hidden'
```
to `containerStyle `
