### ISSUE TITLE
Should return index in onChange

### ISSUE THREAD

**Issue by ydv0121** [hoaphantn7604/react-native-element-dropdown#96]
Hello
Thanks for the perfect DropDown.

I think the DropDown's `onChange` function should return the `index` value too `onChange={(item,index)=>{}}`

**Comment by hoaphantn7604** [comment]
hi @ydv0121 ,
You can filter the data list to find the index.

**Comment by nvacheishvili** [comment]
this actually prevents using async options which would be cool with multi dropdown search... search is not only convenience of the front, it could be used to optimize stuff. would love this feature

**Comment by aurangs7** [comment]
Please implement this feature if possible. I am also looking for it. Instead of looping through the list
