### ISSUE TITLE
Default Value doesn't work

### ISSUE THREAD

**Issue by Kishan-Somaiya** [hoaphantn7604/react-native-element-dropdown#97]
First off all, thanks for an amazing package, 
Default value doesn't work even if we set it and if we use setValue in onChange it only updates the value on alternate clicks. I'm on the current version 2.0.0.

**Comment by Kishan-Somaiya** [comment]
Here's the code :

` import React, { useState } from 'react';
const data = [
    { label: 'Item 1', value: '1' },
    { label: 'Item 2', value: '2' },
    { label: 'Item 3', value: '3' },
    { label: 'Item 4', value: '4' },
    { label: 'Item 5', value: '5' },
    { label: 'Item 6', value: '6' },
    { label: 'Item 7', value: '7' },
    { label: 'Item 8', value: '8' },
  ];
const DropdownComponent = () => {
const [value, setValueDrop] = useState('Item 8');
//I've tried the followings too but they don't work too:
//const [value, setValueDrop] = useState({ label: 'Item 8', value: '8' });
return(
 <View>
            <Dropdown
              data={data}
              labelField="label"
              valueField="value"
              placeholder="Select Value"
              value={value}
              onChange={item => {
                setValueDrop(item.value);
              }}
            />
          </View>
);
}
`

Try the above code it won't load the initial value in the dropdown @hoaphantn7604

**Comment by hoaphantn7604** [comment]
hi @Kishan-Somaiya ,
Refer code: const [value, setValueDrop] = useState('8').
Default value is not a label.

**Comment by rcaraway101** [comment]
```tsx
import React, { useState } from "react"
const data = [
  { label: "Item 1", value: "1" },
  { label: "Item 2", value: "2" },
  { label: "Item 3", value: "3" },
  { label: "Item 4", value: "4" },
  { label: "Item 5", value: "5" },
  { label: "Item 6", value: "6" },
  { label: "Item 7", value: "7" },
  { label: "Item 8", value: "8" },
]
const DropdownComponent = () => {
  const [value, setValueDrop] = useState("Item 8")
  //I've tried the followings too but they don't work too: //const [value, setValueDrop] = useState({ label: 'Item 8', value: '8' });
  return (
    <View>
      {" "}
      <Dropdown
        data={data}
        labelField="label"
        valueField="value"
        placeholder="Select Value"
        value={value}
        onChange={item => {
          setValueDrop(item.value)
        }}
      />{" "}
    </View>
  )
}
```

**Comment by Kishan-Somaiya** [comment]
Thanks @rcaraway101 for formatting the code and sorry @hoaphantn7604, the issue was on my side. Closing this issue now.
